### ISSUE TITLE
[1.8.1-b0] If there is any file on the export folder (or delete old is on), the plugin stops building website.

### ISSUE THREAD

**Issue by hi-jin** [KosmosisDire/obsidian-webpage-export#380] opened 2024-03-01 11:22 UTC
**Describe the bug**
We choose the `export directory` when we set the plugin.
When building website using this plugin, if there is any extra file (even am empty file), the plugin stops.

If we remove all the files on the export directory, it works.
But I think it is little bit uncomfortable for publishing tasks using git. (because of .git directory)

**Operating System**
Mac OS

**To Reproduce**
1. install 1.8.1-b0 version of the plugin.
2. plugin configuration
3. create any file in the export directory.
4. export using the plugin.

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/51053567/2b488695-b07f-4275-aed7-0a65b6bbea23)

In this case, if I remove .DS_Store, it works.

### IMPORTANT: Error Log
see screenshots

**Comment by KosmosisDire** [comment] 2024-03-01 11:24
It is actually any file or is it only files starting with a "."

Both .git and .DS_Store starts with a "."

**Comment by hi-jin** [comment] 2024-03-01 11:29
Any file!

this is an example:
<img width="1459" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/51053567/10922615-4cf9-465e-9941-36f55baa9d04">

**Comment by KosmosisDire** [comment] 2024-03-01 11:32
Okay I think I have an idea of what the problem is. Thanks for the report :)

**Comment by KosmosisDire** [comment] 2024-03-03 02:57
This should be fixed in 1.8.1-1b

**Closed by KosmosisDire** 2024-03-03 02:57 UTC
Labels: bug
