### ISSUE TITLE
An option to disable animations

### ISSUE THREAD

**Issue by lowlight-ua** [KosmosisDire/obsidian-webpage-export#263] opened 2023-10-13 16:13 UTC
It is jarring to have the sidebars slide in every time a link is clicked and the new page is opened.

The animations should be optional; perhaps, a toggle in the settings would be in order.

I considered tweaking the CSS of the exported vault manually, but the animations seem to be embedded pretty deep into the way the page is rendered.

**Comment by KosmosisDire** [comment] 2023-10-13 17:08
Hi thanks, this is a duplicate of #210, so I will close it in favor of that issue. This problem only occurs on files opened locally, and not on a web server.

**Closed by KosmosisDire** 2023-10-13 17:08 UTC
Labels: enhancement

**Comment by lowlight-ua** [comment] 2023-10-13 17:45
I _thought_ I searched for duplicates! Sorry for the noise and thanks.
