### ISSUE TITLE
Unicode character in image paths causes them to not be exported

### ISSUE THREAD

**Issue by SauerkrautAR** [KosmosisDire/obsidian-webpage-export#5] opened 2022-12-19 13:39 UTC
My internal pictures, that are included in the note with ![[picture.png]] are not exported to html. The html file just shows "picture.png". A subfolder for the picture file, as described in the read.mw file is not created either.

Is there a specific way/code, I have to include pictures in the obsidian note?

Thanks

**Comment by KosmosisDire** [comment] 2022-12-19 18:36
Can you include a picture of where your image is in relation to your file, and show a picture of the output, and send the .html file that it output, and include a screenshot of your export settings so I can try to reproduce this?

**Comment by SauerkrautAR** [comment] 2022-12-19 19:43
Sorry I could not find direct messages

Folder:
![folder](https://user-images.githubusercontent.com/121036775/208506164-8e8ccf54-d48e-4d4e-9e82-bb2ea021618a.jpg)
Note "a test"
![note](https://user-images.githubusercontent.com/121036775/208506485-189d4f6a-807b-43af-bd9f-78a01a56fff5.jpg)
Output
![output](https://user-images.githubusercontent.com/121036775/208506544-39c367a4-59af-49d2-9b84-051a2a94fc8c.jpg)

Export Settings
![settings](https://user-images.githubusercontent.com/121036775/208506947-699b3f88-1b6a-488d-8438-2709d802c588.jpg)

HTML File
[a test - Kopie.txt](https://github.com/KosmosisDire/obsidian-webpage-export/files/10262217/a.test.-.Kopie.txt)

Subfolders with the pictures are created during export. The pictures link to my local drive

Thanks a lot for your work!

**Comment by KosmosisDire** [comment] 2022-12-19 21:37
This appears to be caused by the 'ü' character in your folder name. For now you can remove that character temporarily to make it export. (This is because the ü is not part of the ascii character set, so any Unicode character in the file path will break this)

This is definitely a bug though, so thanks for the report and I'll fix this in the future!

**Comment by SauerkrautAR** [comment] 2022-12-20 11:04
Thanks for your help. I changed the ü to ue. Now the pictures are correctly included in the html file. But the pictures are still not exported to a folder. Do I have to change the export settings?

**Comment by KosmosisDire** [comment] 2022-12-20 17:35
Yes, make sure to turn off the inline images option, or else the images will be encoded directly into the. Html file.

**Comment by KosmosisDire** [comment] 2023-01-02 06:32
This issue should be fixed in the latest release, 1.3.1. Let me know if you have any further problems with special characters

**Closed by KosmosisDire** 2023-01-02 06:32 UTC

**Comment by SauerkrautAR** [comment] 2023-01-02 07:05
Thanks a lot for your work.
