### ISSUE TITLE
Export fails when using command with no path or file set

### ISSUE THREAD

**Issue by mcaay** [KosmosisDire/obsidian-webpage-export#226] opened 2023-09-13 20:06 UTC
I chose a simple note but it still doesn't export on macOS. Now the popup window is stuck on "Generating HTML".

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/bae5e2cd-982a-4fc3-911e-96a7bb6841a3)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/d7726e37-83e2-4315-986b-7e5f0312da28)

_Originally posted by @mcaay in https://github.com/KosmosisDire/obsidian-webpage-export/issues/204#issuecomment-1717350867_

**Comment by mcaay** [comment] 2023-09-13 20:08
@KosmosisDire what extra information are you interested in?

**Comment by KosmosisDire** [comment] 2023-09-13 20:13
If you could give:

**Error Log**
1. Please open the developer console using (Ctrl + Shift + I), and clear the console using the button at the top left corner.
2. Reproduce the bug
3. Take a screenshot or copy the error from the console if it has any output and paste it here

**Comment by mcaay** [comment] 2023-09-14 07:07
Ah, sorry, I created the issue from my post, so I didn't see the template :D
I don't have a windows machine to test it.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/e2129fc2-9064-4f3a-a1ff-87fa9524ac48)

**Comment by KosmosisDire** [comment] 2023-09-14 12:47
How are you exporting the files? Are you using the command?

**Comment by mcaay** [comment] 2023-09-14 12:48
Yeah, I'm using this command from command palette.
<img width="702" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/a0ab21b3-f9f8-4727-97c0-c3c3ce6126e6">

**Comment by KosmosisDire** [comment] 2023-09-14 12:52
Have you set an export path using the export model and selected files to export before using the command? Open the export modal with the ribbon icon

**Comment by mcaay** [comment] 2023-09-14 13:07
True, I didn't. Wait, from the ribbon or the 3 dot menu? I don't use the ribbon at all so I hid it completely with css. Now I used the 3 dot menu and managed to successfully export a html note, although the title was missing and my obsidian became unusable - had to force quit it.

I always export single notes though. The three dot menu into "Export as HTML" menu is for multiple notes, so it didn't seem like the menu for my purpose. I don't know what all that means for the current issue.

**Comment by KosmosisDire** [comment] 2023-09-14 15:19
I have encountered the freezing issue and honestly have no idea what causes it. The 3 dot menu is for single files (it just allows you to add more files to the export if you want), it will always open the export dialog with the file you have open selected. The ribbon icon is for multiple files. By the way if you right click on the ribbon it lets you show or hide certain ribbon icons, no need to hide it with css :P

**Comment by mcaay** [comment] 2023-09-14 18:34
> By the way if you right click on the ribbon it lets you show or hide certain ribbon icons, no need to hide it with css :P

I know, but I wanted to get rid of the entire ribbon:
<img width="346" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/bf6ee190-c199-4445-adde-6151e962d03a">

Now I noticed the crash had additional consequences. My local graph from right sidebar got closed and all my group color settings are gone. Also the history of recent notes after pressing Cmd+O is cleared out. That's a bit scary. I sync all my notes and config files to github so I definitely can bring everything back relatively easily, but that might be extra problematic for some people.

**Comment by mcaay** [comment] 2023-09-14 18:37
> The 3 dot menu [...] will always open the export dialog with the file you have open selected.

That doesn't seem to be the case for me. The checkbox for the note I was on is not checked. Tried on a couple of different notes.

**Comment by mcaay** [comment] 2023-09-14 18:49
Yeah, some things in my .obsidian/workspace.json file got a reset to default. E.g. I definitely didn't touch that. Other files didn't get changed.
<img width="1209" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/eb77c142-8b74-450e-b73e-11cab095efed">

**Comment by KosmosisDire** [comment] 2023-09-14 18:56
Very strange, and definetly not good. I will prioritize find a fix for this but like I said I actually haven't figured out what is causing the freeze yet. It has only happened to me a couple of times. Is it happening to you every time? 

As far as the checkbox problem I am not able to reproduce this, the checkbox is always checked. Could you by any chance take a video of this happening in the vault and post it here?

Also I will add a command to export the current note shortly so you will be able to go back to that soon.

**Comment by mcaay** [comment] 2023-09-15 13:51
https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/aa2055da-b53c-485b-b4d7-6f2c4e1b9a7e

**Comment by KosmosisDire** [comment] 2024-02-20 08:11
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:11 UTC
Labels: bug, approved, reproduced
