### ISSUE TITLE
EMBED Note, PDF (PDF's specific page), Section do not appear in HTML export

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#291] opened 2023-11-22 11:27 UTC
Hi,

I do not know whether it needs to be a bug report or a feature request, because I don't know your plugin supports this at all or not. 

Single page/note HTML export.

Try to reproduce:

1. Embed another note
2. Embed a PDF page or its specific page 

Will appear well in Obsidian in both Live Preview and Reading view, but won't be seen in HTML export.

It would be good to have at least for embedded notes. 
Use case: e.g. If sections/chapters of a book are concatenated into a single note document and would be good to see that all in HTML format too.

Thanks for considering or looking after.

![Embed_doesn't_work_2023-11-22](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/85d21c18-263e-4127-8c12-5e329131f216)

**Comment by KosmosisDire** [comment] 2023-11-22 18:11
Thanks this will be fixed in the next update

**Comment by vgyenge6** [comment] 2023-11-23 07:51
Thanks for your notice.

Let me ask, approximately when your next update would be hoped?

**Comment by KosmosisDire** [comment] 2023-11-23 08:12
I'm very very busy, so I would rather not promise any timeline. But I'm still working on it

**Comment by vgyenge6** [comment] 2023-11-23 12:11
Thanks for your answer. Understood :) Still hoping for sooner, because your plugin is very needed.
All the best and good work for you.

**Comment by KosmosisDire** [comment] 2023-12-12 19:09
Is this a duplicate of issue #207?

**Comment by KosmosisDire** [comment] 2023-12-12 19:12
Actually I did not see the PDF problem when looking thorugh the issue before, how do you embed a specific page of a pdf in obsidian? I think I could make it embed the pdf but not just a single page of a pdf as that is a feature of obsidian's custom pdf viewer (unless I also build a custom pdf viewer using pdf.js)

**Comment by vgyenge6** [comment] 2023-12-13 07:40
> Is this a duplicate of issue #207?

Hi, 
Yes, it might be, but I did not notice it earlier, and as I read over this above issue it regarded to earlier versions of both obsidian and your plugin version. (btw: I did not understand exactly what did transclusion mean.)

I opened this ticket (issue) because of I tested it ( once again today too)
in this actual environment
**WIN 10 Pro, Firefox 120.0.1 
Obsidian v.1.4.16
your plugin v. 1.7.3**

and noticed neither 
- the simple other note embed,
- embed section,
- comment of yours regarding to PDF: https://github.com/KosmosisDire/obsidian-webpage-export/issues/291#issuecomment-1852651927
  - full PDF page embed,
  - PDF specific page embed

had exported to HTML **did not work**!

See picture specifically regarded to PDF
![Embed_doesn't_work_2023-12-13](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/50bd2d89-d47f-4b93-8af1-b4ab708b858a)

(* The embeds in obsidian's Reading view and Live Preview are right)

**Comment by KosmosisDire** [comment] 2023-12-13 18:32
Ah right, the pdf embed is coming in the next update as well. I thought I had already implemented it in 1.7

A transclusion is the actual name of the embeded page feature. Transclusions and pdf embeds will work in the next version. However the specific page for PDF's will not work.

**Comment by vgyenge6** [comment] 2023-12-14 07:40
Thanks for your answer, both regarding to the explanation of transclusion and the resolutions coming in the next version. Have a good work. :)

**Comment by KosmosisDire** [comment] 2024-02-20 08:20
This feature has been added in 1.8.0! :)
(PDF's do not support specific pages though, this isn't possible with the default html PDF viewer)
If you find any issues please create a new issue
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:20 UTC
Labels: bug

**Comment by vgyenge6** [comment] 2024-02-21 11:25
Hi,
embed;
- other notes works (however there is inconsistency in the main TOC if an embedded note has headings)
- full PDF even yet doesn't work
- embed section works
I will open a new issue

Thanks for looking after
