### ISSUE TITLE
MathJax breaks upon export

### ISSUE THREAD

**Issue by xFrah** [KosmosisDire/obsidian-webpage-export#102] opened 2023-05-11 17:44 UTC
**Describe the bug**
Immediately after i export to HTML, all the mathjax blocks in the files break. A restart of obsidian turns everything back to normal. Obviously the exported html files also get the broken latex.

I made a video of it.

**Operating System**
Windows 11

**To Reproduce**
Follow this video: https://youtu.be/YgKgNjUAohI

**Screenshots**
![Screenshot 2023-05-11 185951](https://github.com/KosmosisDire/obsidian-webpage-export/assets/37962249/a53385a2-788a-4111-8638-33a1e2d10aa4)
![Screenshot 2023-05-11 191549](https://github.com/KosmosisDire/obsidian-webpage-export/assets/37962249/e408fe32-4412-4d59-bb55-1e5ec750e240)

### IMPORTANT: Error Log
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/37962249/3630ffdb-12bc-4e54-bcfc-7c027bb1262c)
There is nothing else in the console, other than "Finished HTML report."

**Comment by xFrah** [comment] 2023-05-11 17:57
I must also add that like 2 hours ago I discovered that this plugin needed an update so i did it. So I don't really know how many versions this has affected. 
But one thing I'm sure of, is that the version i had before didn't do this ahah.

**Comment by KosmosisDire** [comment] 2023-05-11 18:09
Hey thank you for the report, I'll look into this. Currently the plugin is broken on the latest update which may (or may not be) causing this. Once I get the update to fix it out I will look into this if it is still an issue. Thanks!

**Comment by KosmosisDire** [comment] 2023-05-12 01:32
Actually, this is a duplicate of: #81

**Closed** 2023-05-30 01:54 UTC
Labels: bug

**Comment by KosmosisDire** [comment] 2023-05-30 02:01
This is fixed in update 1.6.0, let me know if you have any more problems! And thanks for the report :)
