### ISSUE TITLE
Add Ignore Folder / Files When Exporting Vault

### ISSUE THREAD

**Issue by BlueBeard63** [KosmosisDire/obsidian-webpage-export#184] opened 2023-09-07 11:24 UTC
**Describe the solution you'd like**
It isnt a problem, but I feel like it would be nice to allow for a setting that would allow you to set folders or files to be ignored when you are exporting the vault as a whole.

**Describe alternatives you've considered**
There isnt really I dont think any good way to do this other than copying out the folders that you dont want to be exported and then exporting the vault.

**Comment by KosmosisDire** [comment] 2023-09-07 14:19
Hi, this is actually a duplicate of a pinned issue! Haha. See: #157

This has already been implemented and will be available in the next update :)

I'll close this for now, but you can create a new issue if needed.

**Closed** 2023-09-07 14:20 UTC
Labels: enhancement
