### ISSUE TITLE
New obsidian version 1.5.8 broke everything

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#373] opened 2024-02-24 01:43 UTC
**Describe the bug**

- On Feb 21, I used 1.8.0-11b to generate [this page](https://people.redhat.com/rsawhill/ai.html), which is perfect.
- Today: my Obsidian [updated to v1.5.8](https://obsidian.md/changelog/2024-02-22-desktop-v1.5.8/) (not sure what it was before)
- Today: I used the same 1.8.0-11b to generate [this broken page](https://people.redhat.com/rsawhill/1.8.0-11b/ai.html)
- Today: I updated the plugin to 1.8.0 and generated [this similarly-broken page](https://people.redhat.com/rsawhill/1.8.0/ai.html)
- Today: I disabled most of my snippets and used 1.8.0 to generate [this equally-broken page](https://people.redhat.com/rsawhill/1.8.0-no-snippets/ai.html)

**Operating System**
Fedora Linux

**To Reproduce**
Uhmmmm. I dunno what to say here. All kinds of things seem to be broken.

**Screenshots**
Not sure what my last version of Obsidian was that generated this:
![good](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/cf49070d-3f8f-45be-a68c-a020b2e9ae9a)

Obsidian v1.5.8 generated this:
![bad](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/e0b4bad2-6f58-4995-80af-4d4e075acd7c)

### IMPORTANT: Error Log
Error log looks scary, but it actually all looks familiar from before.
![console](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/7d0196e3-1248-4b87-b4a1-2f7a14b3d255)

**Comment by KosmosisDire** [comment] 2024-02-24 01:52
I think this is the same issue as, #372 
I am trying to reproduce it but weirdly I cannot

**Comment by KosmosisDire** [comment] 2024-02-24 01:59
I was able to reproduce it, it seems like it isn't including most of the obsidian.css styles for some reason

**Comment by KosmosisDire** [comment] 2024-02-24 05:50
I have fixed it! I'll try and release 1.8.1 tonight

**Comment by KosmosisDire** [comment] 2024-02-25 13:15
I wasn't able to release the fix get, because I am having to fix another more complicated bug before I can release. But as soon as I fix that I will release the next version. 

As a temporary fix you can just copy the `lib/styles/obsidian.css` file from an old export that worked into the new export `lib/styles/` folder.

**Comment by KosmosisDire** [comment] 2024-02-25 20:03
> KosmosisDire, can you please provide an example of the build folder for doing this manually? 
> 
> In my folder I'm uploading to netlify drop I have:
> 
> - "canvasfilename".html
> - obsidian.css
> - ?.js
> 

This fix unfortunately will not work for non web exports. It's possible to manually fix the self contained exports. You need to edit the .html files and add a style tag and paste the contents of an old working obsidian.css file.

I should have the fix out today

**Comment by carbmsanders** [comment] 2024-03-02 19:16
I've been testing this today, and 1.8.1-0b works perfectly with Obsidian 1.5.8, as opposed to Obsidian Webpage Export 1.8.0

**Comment by carbmsanders** [comment] 2024-03-02 19:16
The only problem I'm seeing is that after the initial export, every subsequent export will get hung on 'Building Website' 
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/145479957/d106e97c-3804-4d65-b145-f1c740d15802)

**Comment by KosmosisDire** [comment] 2024-03-03 01:06
> The only problem I'm seeing is that after the initial export, every subsequent export will get hung on 'Building Website' ![image](https://private-user-images.githubusercontent.com/145479957/309495759-d106e97c-3804-4d65-b145-f1c740d15802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MjgyNTAsIm5iZiI6MTcwOTQyNzk1MCwicGF0aCI6Ii8xNDU0Nzk5NTcvMzA5NDk1NzU5LWQxMDZlOTdjLTM4MDQtNGQ2NS1iMTQ1LWYxYzc0MGQxNTgwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwMTA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmFiMTc0YzVhNWYxOGY3ZDcwNmZmN2E0Yzk4OTVmMDdmZGJhZWZiYWJmOTBjNzllNDAyMjNmYjQyMjk0NDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1AkNjeN-QSr6lD3Ie0grXHRNMaYW_ydZ4EXpHxjTqYo)
> 
> EDIT: I found that this was with the Export Mode set to Online Web Server. This works fine with HTML Documents as the export. EDIT2: This happens if you turn 'Delete old files' in Export Options to ON

This is a duplicate of #380

**Comment by KosmosisDire** [comment] 2024-03-03 02:58
> The only problem I'm seeing is that after the initial export, every subsequent export will get hung on 'Building Website' ![image](https://private-user-images.githubusercontent.com/145479957/309495759-d106e97c-3804-4d65-b145-f1c740d15802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzQ5NTgsIm5iZiI6MTcwOTQzNDY1OCwicGF0aCI6Ii8xNDU0Nzk5NTcvMzA5NDk1NzU5LWQxMDZlOTdjLTM4MDQtNGQ2NS1iMTQ1LWYxYzc0MGQxNTgwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwMjU3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTUzMjZjNDBlNzE1MzMxYmMxZDAxOWI1ZTYxYzBhODBiM2FiYjk5OWI5MTQ3MTA2MTdjYjIzZDA3MzFlMDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JddMEBfQcmdmpcaFCiarulxW5ie50Xd-cCU44dLEenw)
> 
> EDIT: I found that this was with the Export Mode set to Online Web Server. This works fine with HTML Documents as the export. EDIT2: This happens if you turn 'Delete old files' in Export Options to ON

This should be fixed in 1.8.1-1b

**Comment by KosmosisDire** [comment] 2024-03-03 02:58
Didn't mean to close this, I will close it once I have released a stable release

**Comment by KosmosisDire** [comment] 2024-03-06 10:00
I went ahead and released a stable release with a patch only for this problem since the beta didn't look like it was coming out soon. Probably is what I should've done to start with.

**Closed by KosmosisDire** 2024-03-06 10:00 UTC
Labels: bug
