### ISSUE TITLE
Regular/scheduled export, via the terminal?

### ISSUE THREAD

**Issue by reagle** [KosmosisDire/obsidian-webpage-export#86] opened 2023-05-04 12:44 UTC
Your exports are quite nice! I'm migrating from zim wiki which has an export via command line, which I invoke on a schedule or before syncing my files to my web host. Is there a similar facility in Obsidian to invoke your plugin via the command line?

**Comment by KosmosisDire** [comment] 2023-05-04 17:37
This is a duplicate of #49 and is planned, thanks!

**Closed by KosmosisDire** 2023-05-04 17:37 UTC
Labels: enhancement
