### ISSUE TITLE
Not exporting the linked content of a note

### ISSUE THREAD

**Issue by ctanas** [KosmosisDire/obsidian-webpage-export#316] opened 2024-01-10 14:47 UTC
I'm using Obsidian to export a note as an HTML file, for my newsletter. Having a home page that gathers content from multiple notes is useful for me, thus using `![[note]]` to get the content of another note is very helpful for me. But when exporting to HTML using your nice plugin, I get a blank area instead of the content. Is there another way to get this functionality? Will it be possible to get the content of another note on export, when using `![[note]]`? Thanks!

**Comment by KosmosisDire** [comment] 2024-01-10 17:41
Hi thanks, this is a duplicate of issue #207

**Closed by KosmosisDire** 2024-01-10 17:41 UTC
Labels: enhancement
