### ISSUE TITLE
 template dynamic script is not supported

### ISSUE THREAD

**Issue by cumany** [KosmosisDire/obsidian-webpage-export#17] opened 2023-01-18 06:28 UTC
For example, write a templater dynamic command in the document ：
`<%+ tp.date.now() %> `
IT Should show the date , but  the tp syntax is exported as is, and not correctly parsed tp syntax When exporting html files

**Comment by KosmosisDire** [comment] 2023-01-18 17:37
Yeah dynamic stuff doesn't do too well. I'll see what I can do about this. Thanks for the report!

**Comment by KosmosisDire** [comment] 2023-02-02 00:25
I am not able to reproduce this. When I export, templater stuff shows up as expected. Could you try in an empty vault with no plugins other that this one and Templater, and on the default theme? Also what OS are you on? And could you send a screenshot of the settings you are using to export? 

Thanks!

**Comment by KosmosisDire** [comment] 2023-02-03 00:27
I am closing this for now, please reopen if it still doesn't work

**Closed by KosmosisDire** 2023-02-03 00:27 UTC
Labels: can't reproduce
