### ISSUE TITLE
Download Unknown.html when going back to previous page.

### ISSUE THREAD

**Issue by junghoon-vans** [KosmosisDire/obsidian-webpage-export#255] opened 2023-10-09 12:47 UTC
**Describe the bug**

I'm hosting my site through vercel.
If I go back on that page, it downloads `Unknown.html`.

**Operating System**
macOS Sonoma 14.0

**To Reproduce**

1. Go to [my site](https://til.vanslog.io).
2. Click on any page to navigate to it.
3. Go to back in your browser.
4. This will download the file without navigating to the previous page.

**Screenshots**
If applicable, add screenshots here to help explain your problem (just copy paste)

**Comment by KosmosisDire** [comment] 2023-10-09 14:09
Hi this is a duplicate of #245, however I will leave it open so I can remember to test with your site as well

**Comment by KosmosisDire** [comment] 2023-10-09 14:14
It seems that this only happens when you go back to an index.html page. Not when you go back to any other page. So that should be an easy fix

**Comment by junghoon-vans** [comment] 2023-10-10 01:29
> It seems that this only happens when you go back to an index.html page. Not when you go back to any other page. So that should be an easy fix

Oh right, this only happens in index.html. Let me see if I can find out what the problem is.

**Comment by XinYaanZyoy** [comment] 2023-12-01 17:25
> It seems that this only happens when you go back to an index.html page. Not when you go back to any other page. So that should be an easy fix

Actually, this happens whenever you go back to the page you launched the site from, which is mostly index.html but not always.

**Comment by KosmosisDire** [comment] 2023-12-01 20:36
Ah thank you, the weird thing is that I can't reproduce this with my own website only with some other people's. So there must be some setting or content that is causing this

**Comment by XinYaanZyoy** [comment] 2023-12-01 20:50
oh! In case you need me, I'm here if you need input from my side to find the issue.

**Comment by TacoV** [comment] 2023-12-07 13:34
Might be a far shot but check if Vercel uses any post-processing of the links - #297

**Closed** 2024-02-20 08:13 UTC
Labels: bug, approved, reproduced
