### ISSUE TITLE
Obsidian inner link to block doesn't  work in HTML export

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#363] opened 2024-02-21 16:22 UTC
Hi,

Obsidian inner link to block doesn't work in HTML export.

Would be expected to work in HTML, because block references in obsidian can function similarly as anchors in HTML.

Thank you for looking after.

Win 10 PRO
Firefox 122.01
Obsidian 1.5.3
your plugin version 1.8.0

**Comment by KosmosisDire** [comment] 2024-02-21 16:25
This is a duplicate of #57. This actually is not possible without adding special support because obsidian keeps track of block locations internally and redirects links programmatically. They do not work using ID's except when they are explicitly defined.

Since this is a duplicate I'll go ahead and close it.

**Closed by KosmosisDire** 2024-02-21 16:25 UTC
Labels: bug

**Comment by KosmosisDire** [comment] 2024-02-21 16:30
To clarify I do plan on adding this. You have also actually reported this before! haha #298
