### ISSUE TITLE
Excalidraw not exporting

### ISSUE THREAD

**Issue by rhusiev** [KosmosisDire/obsidian-webpage-export#217] opened 2023-09-13 09:21 UTC
**Describe the bug**
Excalidraw drawings' embeddings are not being exported. Instead, empty image symbols are shown instead when exported

**Operating System**
Linux(Fedora 38; using latest Obsidian appimage, latest excalidraw and webpage export plugins; tested on flatpak firefox, flatpak brave and native chromium)

**To Reproduce**
1. Create a file with excalidraw files embedded
2. Export the file(or the whole vault)
3. Open the exported html
4. See the broken image placeholder instead of drawings

**Screenshots**
Exported html:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/63148080/68f188b2-67d2-4bfa-9d25-b84ce84229cf)
The note itself:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/63148080/f0e9e7a5-0a70-404d-86bb-2bf6dbdec66c)

### IMPORTANT: Error Log
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/63148080/2c8bed6f-7f4d-4bff-8572-596fc8060af3)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/63148080/b2bf894b-b7d4-4ec4-9292-543b2ad70510)

**Comment by rhusiev** [comment] 2023-09-13 15:16
OK, it can be true. I'll try it on the flatpak version of Obsidian. If it still doesn't work, I'll try to do it on Windows

**Comment by rhusiev** [comment] 2023-09-13 15:20
Didn't work on flatpak, will try on Windows next

**Comment by rhusiev** [comment] 2023-09-13 15:32
Did not work on Windows either

**Comment by rhusiev** [comment] 2023-09-13 15:50
Some time ago(a few months) it worked for me well, but I can't name the exact versions. I tried webpage-export v 1.6 with a few versions of Obsidian and Excalidraw from ~April-June: they exported the first image in a file, but not all the others.

**Comment by KosmosisDire** [comment] 2023-09-13 16:12
Thank you for the thorough testing! It is very helpful

**Comment by Newman5** [comment] 2023-09-30 20:31
> Did not work on Windows either

I'll try this on Windows ...

**Comment by rhusiev** [comment] 2023-10-11 08:27
Has there been any progress on this?

**Comment by KosmosisDire** [comment] 2023-10-11 08:29
Hi, I haven't been able to reproduce this at all and I haven't been able to look into it more

**Comment by KosmosisDire** [comment] 2023-10-11 08:32
I will be able to look into it eventually but it is hard to fix something when I cannot reproduce it. Could you try this in a sandbox vault on a very simple file with only this plugin and excalidraw installed all with default settings on windows?

**Comment by rhusiev** [comment] 2023-10-11 08:33
OK, I'll try it

**Comment by rhusiev** [comment] 2023-10-15 17:51
Here is the empty vault with only excalidraw and webpage export (but on Linux):
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/63148080/16701a34-13ee-466e-9e02-4b3a431a162e)

Next I'll try the same on windows

**Comment by rhusiev** [comment] 2023-10-15 18:03
![Obsidian_wYeIXbLVwl](https://github.com/KosmosisDire/obsidian-webpage-export/assets/63148080/7c981425-0203-49cd-bb54-627fe1a83c18)

Does not work in a clean vault on Windows either

**Comment by KosmosisDire** [comment] 2023-10-15 21:49
Very strange, in this case I am unable to reproduce this however I will see what I can do

**Comment by bretik** [comment] 2023-11-10 14:31
Hi, I have similar issue, except the console errors. So just some additional info, it could help reproducing the issue...

OS: Windows 11
Obsidian: v1.4.16
Excalidraw: 1.9.28
Webpage HTML Export: 1.7.3

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/649117/36caa29c-de9e-4764-bd83-b9678a41ee12)

In the generated HTML, the excalidraw image is missing and the exported HTML image src is referencing `blob:app//obsidian.md/...`:
```html
<img style="max-width:400px" class="excalidraw-svg excalidraw-embedded-img" src="blob:app://obsidian.md/4f44b0e0-6008-4761-951a-54dc12976cde" filesource="Excalidraw/Drawing 2023-11-10 11.38.56.excalidraw.md" w="400" draggable="false" oncanvas="">
```

**Comment by bretik** [comment] 2023-11-20 05:47
I have discovered Excalidraw option `Embedding Exalidraw into you Notes and Exporting` that has `Image type in markdown preview` option set by default to `SVG Image`. After changing this option to `Native SVG`, the embedded Excalidraw drawing is rendered correctly.

**Comment by rhusiev** [comment] 2023-11-21 10:24
> I have discovered Excalidraw option `Embedding Exalidraw into you Notes and Exporting` that has `Image type in markdown preview` option set by default to `SVG Image`. After changing this option to `Native SVG`, the embedded Excalidraw drawing is rendered correctly.

Thank you so much! It fixed the issue!

**Comment by rhusiev** [comment] 2023-11-28 08:29
Should the issue remain opened, because webpage export does not support the default Excalidraw embed option? Or, maybe, I should close the issue and it is the excalidraw's problem?

**Comment by KosmosisDire** [comment] 2023-11-28 13:33
I will leave it open so people can drive the solution easier until the default behavior is better. I might be able to do something to fix this in the future too we'll see

**Comment by KosmosisDire** [comment] 2024-02-20 08:33
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:33 UTC
Labels: bug, can't reproduce

**Comment by myliwenbo** [comment] 2024-07-11 16:25
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/29202248/d6f5992e-ec92-4b01-ba03-446c89e81ddd)
Modify the contents as follows to export normally

**Comment by myliwenbo** [comment] 2024-07-11 16:26
> 我发现 Excalidraw 选项默认`Embedding Exalidraw into you Notes and Exporting`将选项设置为。将此选项更改为 后，嵌入的 Excalidraw 绘图即可正确呈现。`Image type in markdown preview``SVG Image``Native SVG`

thanks
