### ISSUE TITLE
The "Document/Content Width" of "Layout Options" in export configuration can't work as expexted

### ISSUE THREAD

**Issue by eos33** [KosmosisDire/obsidian-webpage-export#127] opened 2023-06-04 02:12 UTC
**Describe the bug**
The "Document/Content Width" of "Layout Options" in export configuration can't work as expexted.
No matter how I changed the "Document/Content Width", the exported html file can't be in larger size.

**Operating System**
Windows 10
Plug-in version: v1.6.0
Obsidian version: v1.3.5

**Comment by KosmosisDire** [comment] 2023-06-04 18:25
Thanks, I'll look into this.

**Comment by KosmosisDire** [comment] 2023-09-20 17:54
Hi, can you verify whether this is fixed in the latest version?

**Comment by zhouxinghong** [comment] 2023-09-24 03:15
The exported html file cannot be displayed in the browser
Windows 10
1.7.3

**Comment by KosmosisDire** [comment] 2023-09-24 03:47
> The exported html file cannot be displayed in the browser
> Windows 10
> 1.7.3

This doesn't seem to be related to this issue at all. Can you try turning on the theme title and try again. And create a new issue.

**Comment by zhouxinghong** [comment] 2023-09-24 03:49
The export interaction logic is very confusing...

**Comment by KosmosisDire** [comment] 2023-09-24 03:51
> The export interaction logic is very confusing...

Hi this is still not related to this issue, could you create a new one please. You will also have to elaborate on which parts are confusing. Just saying that it is confusing doesn't give me anything to work with

**Comment by zhouxinghong** [comment] 2023-09-24 03:53
It seems that your environment is different from ours, and you cannot reproduce many of the problems we submitted...

**Comment by zhouxinghong** [comment] 2023-09-24 03:54
So it doesn't matter whether you submit a new question or not.

**Comment by KosmosisDire** [comment] 2023-09-24 03:59
You are not required to submit a new issue, but I would rather not fill up this comment section with unrelated comments. You do not have to use the plugin and I have no obligation to upkeep it. I upkeep it because I want to. If you are unhappy with it I am willing to do my very best to help, but I am not a magician. If you have constructive and actionable feedback please create a new issue. Thanks

**Comment by KosmosisDire** [comment] 2024-02-20 08:34
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:34 UTC
Labels: bug, not yet reproduced
