### ISSUE TITLE
The table style in blue topaz is inconsistent after exporting in version V1.8.0-1b.

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#326] opened 2024-01-29 09:07 UTC
obsidian version: v1.5.3
Export plugin version: V1.8.0-1b
Theme used: blue topaz

The new version of the plugin has made the left and right sidebars more attractive and beautiful after exporting.

However, I encountered the following problem: the plugin changed my table style after exporting.

I do not like this alternating display of the table header. Is it possible to solve this issue?

This is the editor view:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/01abe131-1b7b-4606-8a0b-1c6d9d72f5fe)

This is the view after exporting:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/0fe6b00a-8476-418b-853f-533723520c63)

Additionally, for the sake of document aesthetics, I have set the table width to 100% in blue topaz. However, after exporting, the table does not appear to have the same 100% width as it does in the editor.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/3117db29-3dff-48f6-9965-43f4874297b7)

There is another issue where, when clicking on the table of contents on the right side, it no longer jumps to the specified location in the document.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/ef3f3028-5135-4454-8621-05cdd4c5c577)

**Comment by zhoulonghao520** [comment] 2024-01-29 09:17
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/560d656e-1b9b-496f-b4dc-549be506102a)
It is more aesthetically pleasing for all columns of a table to have the same color. I'm not sure why they have different colors now.

**Comment by KosmosisDire** [comment] 2024-01-29 09:39
This is probably due to #325

**Comment by KosmosisDire** [comment] 2024-01-29 09:44
Try and see if it is fixed in 1.8.0-2b

**Comment by KosmosisDire** [comment] 2024-01-29 09:48
Can you send me the snippet you used to change the tables? Also would it be possible for you to send a link to your hosted site? It would be helpful to diagnose the problem of the outline not jumping to the clicked header.

**Comment by zhoulonghao520** [comment] 2024-01-29 09:55
I am using the Blue Topaz theme and the Style Setting plugin. I have set the table width to 100% in the Style Setting plugin.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/214aa430-89bc-48d2-934a-44df3f659e84)


![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2463cd21-6120-4be3-a506-fa9fb63248fb)

Table is not using fragments.

**Comment by KosmosisDire** [comment] 2024-01-29 10:20
Ah okay I see, this may still be a problem with the loading order of the css. Try and see if it is fixed in 1.8.0-2b, but I will fix this in the next update if not. Thanks

**Comment by zhoulonghao520** [comment] 2024-01-29 10:26
I am using V1.8.0-2b.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/c0d4a128-f689-4581-ad48-25d16e1cb26f)

Now the table's colors are displayed correctly.

However, the 100% width is still not working. 

I will try the new version when you update it.

**Comment by zhoulonghao520** [comment] 2024-01-29 10:29
Additionally, why is it that starting from version V1.7, the export speed has become very slow? I have been using version V1.6.0 because the export speed is very fast.

**Comment by KosmosisDire** [comment] 2024-01-29 10:34
Could you give me an idea of how long your export is taking? Maybe you could show a video of the export on the old version and on the new version so I can see the difference. For me it is much faster.

**Comment by zhoulonghao520** [comment] 2024-01-29 10:37
I wonder if the slowdown in export speed is caused by the large number of errors and warnings in my old documents? 

When I create a new document with a lot of content, it doesn't become too slow.

My old documents have many embeds and I have used a lot of plugins.

**Comment by zhoulonghao520** [comment] 2024-01-29 10:42
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/1b347835-8d7c-40fa-801e-1efc4856a2c4)
I am using that too. When using the online mode, there is floating text on the document, but I don't understand what that prompt means.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/5656f9f7-b4bb-43c0-9790-b30ab0aea140)

**Comment by KosmosisDire** [comment] 2024-01-29 10:44
Ahh, okay so you are opening your files locally. In that case you should be using the HTML Documents export just like you are. That export mode is definetly much slower, because I have updated it to actually include a bunch of resources that were not being included before. Sometimes it doesn't need those resources, but a lot of times it does and it breaks if they are not included.

**Comment by zhoulonghao520** [comment] 2024-01-29 10:47
According to the prompt, it seems that I need to deploy this file as a web application. When using v1.8.0-1b, I copied the exported file to my IIS directory and tried to access it via HTTP, but it couldn't be opened. That's why I switched to another export mode. Perhaps I can give it another try and put it back in the IIS directory to see if it works now.

**Comment by KosmosisDire** [comment] 2024-01-29 10:48
If you are accessing it via http is should work, and you should use the Online Web Server option. If it doesn't work let me know so we can solve that problem first.

**Comment by zhoulonghao520** [comment] 2024-01-29 10:56
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/fedb7f4a-3c80-4627-87e2-18f76a7170f9)
Great! I think last time I couldn't access it because I might have missed some files and didn't copy the complete file to my IIS server. I gave it a try now by exporting using the first option, and it was incredibly fast. That's wonderful!

**Comment by KosmosisDire** [comment] 2024-01-29 10:59
Awesome! If you want it to be even faster you can also scroll to the experimental section in the settings and enable "Only export modified". It will make small changes blazingly fast.

**Comment by zhoulonghao520** [comment] 2024-01-29 11:03
Once the new version resolves the CSS loading issue, I believe I can officially start using the new version of the tool. In fact, I have been keeping an eye on updates for this plugin, and every time there is an update, I try it out on my virtual machine. However, currently I am still using V1.6.0. The new V1.8.0 version with the collapsible panels looks much better. I will try it again tomorrow morning to see how it handles various embeds.

I appreciate your respect and admiration. This plugin has been extremely helpful for my work.

**Comment by KosmosisDire** [comment] 2024-01-29 11:09
Thank you :) 
All the embeds should be working now! Let me know if any aren't.

**Comment by zhoulonghao520** [comment] 2024-01-30 01:33
<img width="1772" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/e4ef2d40-caa8-4069-b2bd-c7e6cf3a7a9c">

When I deployed IIS to my cloud server in the morning, my colleagues told me that it took about half a minute for them to access it successfully. Is this normal?

Why does this version have such a long loading time?

**Comment by KosmosisDire** [comment] 2024-01-30 02:13
Are you sure you exported it in Online Web Server mode? I can't say why yours is loading slow without having access to it or having a way to reproduce it. But I can say that my vault (https://notes.nathang.dev) does not load slowly for me. You can test mine out if you'd like to see if it works well for you?

If you've done everything right it should load very fast, unless there is some bug that's stopping it from loading

**Comment by zhoulonghao520** [comment] 2024-01-30 02:24
<img width="1780" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/dd73f4b3-c5e9-49b8-b364-e7f3125aae79">

Thank you for your prompt reply. I have two more questions, which may be related to the way you implemented the left-side file navigation (I speculate that you used JavaScript to read the folder instead of generating HTML directly).

1. After updating the left-side file navigation, it requires clearing the browser cache to view it properly. This means that every time there is an update to the document, I have to notify the readers to clear their browser cache in order to see the latest version or ask them to view it in Chrome's cache-less mode.

2. It might also be the CSS loading issue you mentioned yesterday. Currently, when I export my document, there are still many instances of page distortion occurring.


This makes me really look forward to your next version and the official release. It will greatly enhance the user reading experience.

**Comment by zhoulonghao520** [comment] 2024-01-30 02:38
https://notes.nathang.dev/

What theme is used for this?

**Comment by KosmosisDire** [comment] 2024-01-30 05:07
I am using the Flexoki theme, it's actualy made by kepano (the ceo of obsidian). It's a very simple theme.

**Comment by KosmosisDire** [comment] 2024-01-30 05:11
> After updating the left-side file navigation, it requires clearing the browser cache to view it properly. This means that every time there is an update to the document, I have to notify the readers to clear their browser cache in order to see the latest version or ask them to view it in Chrome's cache-less mode.

You are right the sidebar is fetched with a http request. Most browsers support a shift+F5 or ctrl+F5 to reload a webpage with a cleared cache. However I haven't usually had a problem with this. I suppose I could set that to never be cached but that would cause the page to load slightly slower all the time.

> It might also be the CSS loading issue you mentioned yesterday. Currently, when I export my document, there are still many instances of page distortion occurring.

It is really hard for me to know what is causing this without some kind of way to reproduce it. If you could give me instructions for how I could reproduce the problem myself I can acually try and fix this. I don't think it is due to a css loading order issue, but I suppose it is possible.

**Comment by zhoulonghao520** [comment] 2024-01-30 05:50
I would like to give you my plugin list and theme list files.

I will also provide you with a compressed file containing the problematic document content later, so that you can reproduce the issue.

**Comment by zhoulonghao520** [comment] 2024-01-30 05:52
I believe that providing you with the plugin list, theme list files, and the document content where the issue occurred is necessary for reproducing the problem. When I have time, I will organize them and send you a RAR file.

**Comment by KosmosisDire** [comment] 2024-01-30 06:06
Okay, that will be helpful, thanks

**Comment by zhoulonghao520** [comment] 2024-01-30 08:34
[ObsidianFile.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/14094933/ObsidianFile.zip)

This is my plugin directory, theme directory, and also the directory with the documents that are displaying abnormally. You can take a look. Why are they not displaying properly?

**Comment by zhoulonghao520** [comment] 2024-01-30 08:37
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/0543bc6b-cdfa-4dcf-85d4-8146971bf753)

After exporting, if the table width is not to 100%, it will be displayed abnormally.

**Comment by zhoulonghao520** [comment] 2024-01-30 08:42
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/8581c9ca-75f5-447f-89e3-925280898438)

I often use Sheets Extended to create complex tables because it allows me to conveniently set the width of the tables. This helps make my documents look consistent. However, after exporting in version V1.8.0-2B, there is a space between the table header and the table body. I'm not sure what the reason for this is.

**Comment by zhoulonghao520** [comment] 2024-01-30 09:04
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/b45c9876-695e-4579-b870-4df56af765b0)
Clicking on the title does not navigate to the corresponding location.

**Comment by ryran** [comment] 2024-01-30 16:29
> Clicking on the title does not navigate to the corresponding location.

Ooo interesting this sounds the same as #328

**Comment by KosmosisDire** [comment] 2024-01-30 16:50
> > Clicking on the title does not navigate to the corresponding location.
> 
> Ooo interesting this sounds the same as #328

Yes I think so

**Comment by KosmosisDire** [comment] 2024-01-30 21:24
I was able to fix both these problems, I will release another beta in just a bit

**Comment by zhoulonghao520** [comment] 2024-01-31 03:26
Great, You are really amazing.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/326902d0-31a3-4513-94b6-63bc5728472a)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2b69cb52-f5d5-4d5d-b9f3-824ea3307b22)

Is it possible to embed flowcharts created with Excalidraw into a webpage without being visible? Can this issue be also resolved?

**Comment by KosmosisDire** [comment] 2024-01-31 20:00
> Is it possible to embed flowcharts created with Excalidraw into a webpage without being visible? Can this issue be also resolved?

Excalidraw is supported. Are you trying to do something that isn't working?

**Comment by zhoulonghao520** [comment] 2024-02-01 01:32
[TEST.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/14119150/TEST.zip)

I'm not sure why, but after embedding it into other documents, it becomes invisible when exported.

Attached is the content of the note I tested.

**Comment by KosmosisDire** [comment] 2024-02-01 01:43
I'll take a look

**Comment by zhoulonghao520** [comment] 2024-02-01 02:01
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/67bc79b3-7732-4a13-9d7a-5300b6f158d0)

OK ,thanks!

**Comment by zhoulonghao520** [comment] 2024-02-01 02:40
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/6ae43279-a59c-450c-81eb-ac217d78eac9)

https://github.com/NicoNekoru/obsidan-advanced-table-xt/issues/51

The issue of spacing between the table header and table body is caused by another plugin. I have already resolved this problem by using a CSS snippet. I have also provided feedback to the plugin's author.

Initially, I mistakenly thought it was an issue after exporting, but in reality, the spacing is present even without exporting. Therefore, it is not related to your plugin. I believe there is no need for you to handle this.

Here is the CSS snippet I used to fix the issue:

```css
.className tr:not(:has(td)):empty {
  display: none;
}
```

**Comment by KosmosisDire** [comment] 2024-02-01 06:00
@zhoulonghao520 As for the excalidraw problem see here: #217 
The solution is to change the excalidraw embed mode to Native SVG in the settings.
I have added a warning to the plugin that will notify the user of this if it is detected that this setting is wrong.

**Comment by KosmosisDire** [comment] 2024-02-02 01:33
Test this on 1.8.0-3b and let me know how it works

**Comment by zhoulonghao520** [comment] 2024-02-02 02:16
V1.8.0-3b

<img width="1791" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/a6b14c22-9cc7-4649-b563-dcaa5d7d1e35">

Have you completely disabled opening and viewing documents locally? Currently, when I try to open them locally, they appear blank.


This is the result I posted on my cloud server.

http://119.23.215.142:8099/%E6%B5%8B%E8%AF%95%E6%96%87%E6%A1%A3/%E6%96%87%E6%A1%A3.html

**Comment by KosmosisDire** [comment] 2024-02-02 02:19
Ah sorry they should not appear blank, I will fix that.  The link you posted doesn't work because of the encoding it seems? However it looks like the problem is that all the tables are centered?

**Comment by KosmosisDire** [comment] 2024-02-02 02:21
I should be able to reproduce this using the tests you sent me before, I forgot to test it on your page before releasing it

**Comment by zhoulonghao520** [comment] 2024-02-02 02:22
<img width="1785" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/3d49b992-39fd-4a11-8e40-3807926d95db">
I can't find this title on the page anymore.

**Comment by KosmosisDire** [comment] 2024-02-02 02:24
Is that the only problem? Or are the tables supposed to be like they were before?

**Comment by zhoulonghao520** [comment] 2024-02-02 02:35
I set the table width to 100% in the theme for my software requirement document to maintain consistency and improve the overall appearance. In version 1.6.0, the exported result is identical to what I see in the note-taking software.

In plugin version 1.8.0, after exporting the table, the width effect is not preserved. As a result, the document appears messy. If you are unable to resolve this issue in the short term, I think I can temporarily solve it by using CSS code snippets to set the CSS width for each table plugin.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/9e287cfe-a47e-4ff9-a69a-c74d0fa208f8)

There is another issue with the embedded Markdown document shown in the screenshot. After exporting, it is not displaying correctly.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/9a37de4b-79a6-4ffd-9510-8b67b9154e1b)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/bc0ca1ba-6e29-42fb-a2db-ca61cfe6f784)

However, this issue, even if it is not resolved, will not have a significant impact because there are rarely any cases where flowcharts and tables need to be drawn simultaneously. If such a situation arises, alternative drawing tools can be used.

When using the online mode, the export speed is very fast, which is fantastic.

**Comment by zhoulonghao520** [comment] 2024-02-02 03:17
Problem 1: Opening locally shows a blank page.
Problem 2: Clicking on the sidebar when opened locally does not have any response.
Problem 3: The table width cannot follow the 100% width effect of the Blue Topaz theme.
Problem 4: The table cannot be aligned to the left.

I feel that problems 3 and 4 are both related to the theme.

**Comment by KosmosisDire** [comment] 2024-02-02 03:34
I just fixed issues 3 and 4, it was a very sneaky bug. Problem 1 should be easy to fix.

Is problem 2 in an "HTML Documents" export or an "Online Web Server" export?

**Comment by zhoulonghao520** [comment] 2024-02-02 03:39
Hello, for problem 2, I am using the "Online Web Server" option.
<img width="1781" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/04071f14-8650-4a2b-a55f-b9d4e728b45f">
<img width="1789" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/ac1001ca-3316-4e7b-b860-dbdddf043b88">

**Comment by KosmosisDire** [comment] 2024-02-02 03:56
The sidebars aren't really meant to work if you open a web server export manually. But I can try and make that script load even when it is opened locally.

I will make sure the content displays though, because that can be very useful just to make sure it looks correct.

**Comment by zhoulonghao520** [comment] 2024-02-02 04:01
There is a requirement in my work to upload documents to SVN for archiving.

It seems that I need to use either the "HTML Documents" mode or the "Raw HTML Documents" mode.

I will export the documents again and then archive them.

Without the proper functioning of the sidebar, the document structure diagram is not easily accessible, which is inconvenient.

Thank you for your prompt response.

Looking forward to the next version...

**Comment by KosmosisDire** [comment] 2024-02-02 04:13
The sidebar should work fine in HTML Documents or Raw HTML Documents mode, just not in the Web export mode

**Comment by zhoulonghao520** [comment] 2024-02-02 04:38
Yes, that's correct. The export process takes a bit longer. I tried it yesterday.

**Comment by KosmosisDire** [comment] 2024-02-02 04:41
There is a reason that web exports should not be viewed locally, because they fetch various parts of the page using http and that is not supported when the file is opened locally. So there are a number of things that do not work. This is why you need to export "HTML Documents" mode instead. I know it takes much longer, but that is because it is inlining all the information it needs so it does not require http requests on the client.

**Comment by KosmosisDire** [comment] 2024-02-02 04:42
A future goal is to make these offline exports much faster by embedding all the exported documents into a single html file. This way the one html file can be opened to view the whole vault. This would allow much faster exports because it reduced duplication of data, and it would be more convenient for sharing.

**Comment by zhoulonghao520** [comment] 2024-02-02 04:59
You have solved the issues I brought up. I will upgrade my Obsidian version to V1.5.3 and use this plugin when you release the next version.

Thank you very much for your plugin, it has been very helpful for my work. I primarily use it for writing software requirement documents.

**Comment by KosmosisDire** [comment] 2024-02-02 05:53
So after looking through your files and trying my best to fix them, I think that a lot of your problems are coming from your snippets and the theme. There is a bunch of really weird styles applied to the tables and headers that mess everything up even in obsidian. It's less noticable in obsidian, but it messes up some export stuff too.

I have it looking mostly correct now, and I will release a new beta with those fixes, but I can't really do anything else to make it work better past this I don't think (unless you find more bugs of course)

**Comment by zhoulonghao520** [comment] 2024-02-02 06:09
If there are any other usage errors, I will try to solve them using CSS snippets. Thank you very much! 😊 I really love the folding effect in V1.8.0. It makes document viewing more convenient and allows for more content to be displayed.

These CSS snippets were specifically written to address issues I encountered in Obsidian v1.3.5 + 1.6 plugin. Now, I think these code snippets may no longer be necessary.

**Comment by zhoulonghao520** [comment] 2024-02-02 06:24
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/b0951882-063c-4835-af94-991f895f2f92)
I wrote this CSS to hide the left sidebar when publishing.

/*Automatically generate headings based on page titles*/
.pagename-auto-title,
.pagename-auto-title a
{
  color:black !important; 
  font-size: 40px !important; 
  text-align: center !important; 
}

For example：
`.pagename-auto-title`-需求规格说明书<br/>[[存货台账]]

This is to automatically update the titles in the document when the file name is changed.

/*Remove the blank lines below the embedded file.*/
.markdown-embed-content div {
    min-height: 0px !important;
}


/*Adjust the distance between the table and the heading because the table in the theme is a bit far from the heading.*/
:is(.markdown-preview-section,.markdown-rendered) table:not(.dataview.table-view-table) {
    border-collapse: collapse;
    overflow: auto;
    float: left;
    margin-left: 0px !important;
    margin-top: 0px !important;
    margin-bottom: 8px !important;
    min-height: 0px !important;
}



<img width="1263" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/a34b668f-489f-4f76-8bdd-6061f82e32d1">

/* Prevent the heading from moving behind the table. */
.document-container h1 {width: 100% !important;}
.document-container h2 {width: 100% !important;}
.document-container h3 {width: 100% !important;}
.document-container h4 {width: 100% !important;}
.document-container h5 {width: 100% !important;}
.document-container h6 {width: 100% !important;}



/*Distance between asciidoctable and the heading.*/
.asciidoc-blocks-parent p.tableblock {
    margin-top: 0px;
    margin-bottom: 0px;
}



These are the main CSS snippets. With OBSIDIAN V1.3.5 + 1.6 plugin, these snippets can make the originally abnormal displays appear normal.

**Comment by KosmosisDire** [comment] 2024-02-02 06:32
Do you know about the setting under `Settings > Appearance > Show Inline Title` which displays the file's name as the top header?

I think most of these styles are out of date now or broken. When I export your site without your snippets everything works fine with no broken or distorted page elements. As for the sidebar that has changed as well.

By the way, if you want certain styles to apply only to the exported pages, you can prefix them with "publish", like so:

```css
/* Hide left sidebar */
publish .sidebar-left
{
    display: none !important;
}

```

Of course this example doesn't need the prefic because .sidebar-left doesn't exist in obsidian, but hopefully you understand the point.

**Comment by zhoulonghao520** [comment] 2024-02-02 06:40
Indeed, they are outdated because those styles were specifically written by myself to address display issues based on versions V1.3.5 and V1.6 of the plugin.

Regarding your suggestion about the settings, my file titles have a fixed prefix followed by the document name. For example:

业财软件信息系统_v1.0—01库存优化
业财软件信息系统_v1.0—02先进先出法与增加源单编号
业财软件信息系统_v1.0—03先进先出法与增加源单编号

/* Hide left sidebar */
publish .sidebar-left
{
    display: none !important;
}

This was mainly written to embed the operation manual into our web application interface. Now that there is a folding feature, I no longer need to write CSS snippets specifically to hide the left sidebar.

As you mentioned, these code snippets are no longer needed.

**Comment by KosmosisDire** [comment] 2024-02-02 06:54
@zhoulonghao520 Okay I just pushed 1.8.0-4b with those changes, let me know how that goes and if there's anything I missed!

**Comment by zhoulonghao520** [comment] 2024-02-02 07:22
<img width="1761" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/f061c335-6a67-442d-9449-8a6ad8ed29de">

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/80954305-155d-4245-8896-867542586cc2)

The document width setting is not working locally.


<img width="1794" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/efceea5f-2564-41b8-8797-b0850f251e0a">

After publishing, nothing is visible.

http://119.23.215.142:8099/demo/doc.html

**Comment by KosmosisDire** [comment] 2024-02-02 07:26
I noticed the content width wasn't working, I'm working on fixing that. As far as the content not loading could you try just temporarily including a custom head content html file with some content in it? See if including that head content will allow it to load

**Comment by KosmosisDire** [comment] 2024-02-02 07:30
I also released version 1.8.0-5b which might fix the content not loading

**Comment by KosmosisDire** [comment] 2024-02-02 07:34
As another side note, you should only ever use one H1 header per document. The H1 header is meant to be used as a title or a tob level heading that contains all other content. Thus it is not collapsable. I noticed you are using multiple H1's which causes parts of your document to not be collapsible.

**Comment by zhoulonghao520** [comment] 2024-02-02 07:37
http://119.23.215.142:8099/demo/doc.html
1.8.0-5b

<img width="1796" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/07ae274d-4a00-4492-9bff-3591f24abf9f">

**Comment by zhoulonghao520** [comment] 2024-02-02 07:50
<img width="1789" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/c618ed90-4119-4045-a8b8-603bef1485e9">

I noticed the collapsing issue in the table of contents in previous versions, but it doesn't affect usability. In fact, I believe that keeping the first-level headings uncollapsed is more convenient for others to read.

**Comment by KosmosisDire** [comment] 2024-02-02 08:07
I released 1.8.0-6b which I believe should fix your problem, but I cannot reproduce your problem so it's possible it won't fix it. It does fix the content width problem though.

**Comment by zhoulonghao520** [comment] 2024-02-02 08:18
<img width="1759" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/e545c67a-9300-4be4-98bc-853694f16a57">
When opening the file locally, the width setting is now taking effect.

**Comment by KosmosisDire** [comment] 2024-02-02 08:27
Ah I think I figured it out, let me release another one haha

**Comment by zhoulonghao520** [comment] 2024-02-02 08:29
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2a7b89de-082c-4506-b2a6-587039b9121e)
I noticed that there is a "hide" here. If you remove this "hide", it will be displayed.

**Comment by KosmosisDire** [comment] 2024-02-02 08:32
Yes, the hide is being removed, the problem is actually just that something else is preventing it from initializing the page

**Comment by KosmosisDire** [comment] 2024-02-02 08:44
Okay check out 1.8.0-7b! I think that should actually fix it haha

**Comment by KosmosisDire** [comment] 2024-02-02 08:47
Also if this doesn't work or you find any new problems, it would probably be good to close this issue and start a new thread. This thread is getting very very long

**Comment by zhoulonghao520** [comment] 2024-02-02 09:18
All issues have been resolved. Closing it now.

**Closed** 2024-02-02 09:18 UTC
Labels: enhancement

**Comment by KosmosisDire** [comment] 2024-02-02 09:25
Awesome! Glad it's working :)
