### ISSUE TITLE
Internal links do not work when using the file:// protocol

### ISSUE THREAD

**Issue by thehirou** [KosmosisDire/obsidian-webpage-export#66] opened 2023-04-29 11:19 UTC
[Video](https://youtu.be/DmK88uunDVI)

I'm not sure if it is too soon to open a issue since this has been updated like 30 minutes ago, but here you go.

The first issue is that there is now a notable delay when clicking a hyperlink (Not locally, since locally it straight up doesn't work) and if you click multiple times before it gets to load, the URL bar duplicates part of it, making it so that when it loads and you go back, it shows "Page doesn't exist!" (Example at 00:42 from video)

Other issue is that hyperlinks don't work locally, you have to either middle click or right click -> open in new tab. In the video, the first tab is a local test and the second tab is a test hosted in GitHub pages, it works there but with notable delay, as previously mentioned.

I tried different web browsers and they give me the same problem.

_(Edit: Don't worry about empty notes, the ones I clicked and were empty were supposed to be empty.)_

Let me know if you need any more info about these issues if I didn't make myself clear. Thank you!

**Comment by KosmosisDire** [comment] 2023-04-29 11:29
No problem with the fast issue haha, this is interesting this is all working on my end. Are there any error in the console when you click on a hyperlink for the first time? You can open it with `ctrl+shift+j`. 

Can you test this page and tell me if it is doing the same thing?https://nathang.dev/fileshare/misc/graph_view_demo/docs/plugins/core-plugins.html

As for the clicking the link multiple times, I can reproduce that and it is something I can fix.

Thanks for the report!

**Comment by KosmosisDire** [comment] 2023-04-29 11:34
Ahh, it is a problem with it being over the file:// protocol. In other words you have the file opened on the local filesystem so it can't load the files correctly. I will have to implement a fallback method for the file:// protocol

**Comment by thehirou** [comment] 2023-04-29 11:44
Cool! I'm not sure if you asked me to test that page to check the other issue but anyway that one works fine, maybe my delay problem comes from having a lot of audio files and images.

**Comment by KosmosisDire** [comment] 2023-04-29 11:52
I didn't notice any delay in the video, what is the delay you are talking about? From what I can tell the problem is just that the links are not doing anything when clicked (and there is a bug when you click a link multiple times)

**Comment by thehirou** [comment] 2023-04-29 11:57
In the video I clicked the hyperlink "Risotto" at 1:04 and it opened at 1:09. As I said, this only happens when it's not being ran locally, since the only way to open a link by normal clicking is when I host it (?

**Comment by KosmosisDire** [comment] 2023-04-29 12:27
Ah okay I see that now, I will see what I can do about that but I suspect it may just be a slow connection?

**Comment by KosmosisDire** [comment] 2023-04-29 12:35
@thehirou Could you host your webpage with the new update so I can take a look at it, it might help me figure out what is causing the lag

**Comment by thehirou** [comment] 2023-04-29 12:43
Sure, here you go:
https://thehirou.github.io/expired-milk/PROJECT/PROJECT_Index.html

**Comment by KosmosisDire** [comment] 2023-04-29 12:48
@thehirou Most pages open quite fast for me, and I don't have the problem with the links getting corrupted when clicking rapidly. Could you try going into the main plugin settings and turn off all the inlining options? That should make the export much faster and it should make the pages load much faster as well. That may help the load time. Everything seems to be normal, it just is taking a little while to load the page before showing it.

**Comment by KosmosisDire** [comment] 2023-04-29 12:49
@thehirou Also if you full reload obsidian, the problem with links not being clickable when opening the file locally should be fixed.

**Comment by KosmosisDire** [comment] 2023-04-29 12:54
Okay yeah the problem is that you have a lot of embedded files in your documents and since you have inlined everything all of those files are being loaded and you have to wait for it to load before it will show the page. Removing inlining is the solution.

**Comment by thehirou** [comment] 2023-04-29 13:01
You're right, this is loading beautifully now, thank you so much for your time!

**Comment by KosmosisDire** [comment] 2023-04-29 13:04
Okay great! No proble, and thanks for reporting the issue :)

**Closed** 2023-04-29 13:06 UTC
Labels: bug
