### ISSUE TITLE
Export of linked Files

### ISSUE THREAD

**Issue by kwetter** [KosmosisDire/obsidian-webpage-export#47] opened 2023-03-09 08:55 UTC
Is it possible to export linked (.md-) files within a document. Maybe as a checkbox to choose from when exporting. As of now, all links created are clickable in the HTML but lead to an unknown file. 
Maybe i just don't get it and need some kind hints. Thanks!

EDIT: I know of the export folder/vault function. This is not what i am looking for as I eitehr don't have the selected documentsin one folder or i just don't want the whole vault to be exported. As said: A checkbox selection of all linked files within the document would be great.

**Comment by KosmosisDire** [comment] 2023-03-09 16:05
Hi! Thanks for the feature request. This is a duplicate of #38. 

This is a planned feature, but it may be a little while.

**Closed** 2023-03-09 16:07 UTC
Labels: enhancement, duplicate
