### ISSUE TITLE
Requesting optimizations in future versions.Reduce the border size of the collapsible panel to make the display more visually appealing.

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#273] opened 2023-11-03 02:25 UTC
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2b95f64d-11ce-4325-813f-176388373e35)

Hello, I would like to inquire if there will be any optimizations made to the border in the upcoming versions. Currently, the border width is quite wide and does not look as aesthetically pleasing

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/a3514085-b84c-45a9-b73d-94da4fd8ae7f)

Additionally, I have also noticed a blank space at the top when using version v1.7.3.

Your plugin has played a significant role in my work, Thank you very much for your contributions!

**Comment by KosmosisDire** [comment] 2023-11-03 02:32
Hi you can always adjust the styles yourself to make them look how you'd like. If I make it thinner it becomes harder to click on as the icons become smaller. But again you can change it however you'd like using snippets. I will look into the spacing issue

**Comment by KosmosisDire** [comment] 2023-11-03 02:34
I think the spacing is actually caused by your theme. Try this with the default theme or the minimal theme and let me know if this is still a problem.

**Comment by zhoulonghao520** [comment] 2023-11-03 02:40
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/d7ae63a7-afb9-4307-bf6c-5404d6c8d888)
The above is the effect of switching to the default theme

**Comment by zhoulonghao520** [comment] 2023-11-03 02:57
<img width="719" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/ec57a343-0e60-4b17-ba97-443fe5faa7b7">

Thank you very much for your response. I have found it. I rewrote the style and achieved the desired effect.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/e362e082-c064-42a3-8391-125628929177)

**Comment by zhoulonghao520** [comment] 2023-11-03 03:05
<img width="1472" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2c31d5a4-f73c-428b-8265-6215227d67ec">

I found it. You have written the styles in the JS file. I can make the changes directly in there. Thank you very much for your response. That's great!

**Comment by KosmosisDire** [comment] 2023-11-03 03:43
> ![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/d7ae63a7-afb9-4307-bf6c-5404d6c8d888)
> The above is the effect of switching to the default theme

This is just the natural margin between the document and the top of the page I believe

**Comment by zhoulonghao520** [comment] 2023-11-03 03:52
<img width="1787" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/58864908-819c-44e9-89aa-9102345614f4">

Why does the sidebar float above the content when I use it on a smaller resolution, but not on a larger one? In fact, I don't need this floating effect because it obscures some content. It's not very convenient for reading.

**Comment by KosmosisDire** [comment] 2023-11-03 12:32
Because on a small resolution there is not enough space for the document and both sidebars to be open at once. So it makes them float so they don't squish the content down tiny if you open both at once.

**Comment by KosmosisDire** [comment] 2023-11-03 12:34
Also keep in mind that if you change the styles in the js file then all your changes will be overwritten when you update in the future. Just use snippets to override certain styles.

**Comment by KosmosisDire** [comment] 2023-11-03 12:35
You can disable the floating effect with styles as well. There is a class for floating sidebars. But keep in mind that this will completely break your website on mobile!

**Comment by aubreyz** [comment] 2023-11-03 16:19
Somewhat tangentially, I'd be in favour of a simpler option that has no sidebars at all, with content taking up full width (optionally constrained to some maximum), and then with a top navigation bar with a half a dozen links defined by the user to whatever pages).

**Comment by KosmosisDire** [comment] 2023-11-05 04:15
> Somewhat tangentially, I'd be in favour of a simpler option that has no sidebars at all, with content taking up full width (optionally constrained to some maximum), and then with a top navigation bar with a half a dozen links defined by the user to whatever pages).

In the next update you will be able to generate pages with no extra content other than the document. You will also be able to inlcude custom head content including scripts. This could be used to generate the top navigation bar. Or you could use something like PHP. 

I likely will not add specific support for a top navigation bar soon, but thank you for the suggestion.

**Comment by aubreyz** [comment] 2023-11-05 15:51
Sidebar-free multifile output sounds ideal!

**Comment by zhoulonghao520** [comment] 2023-11-06 03:18
Thank you for your reply. I will try to modify the style fragment of the sidebar. The current effect is still very good even when collapsed on larger screens. I am looking forward to your upcoming updates, and I believe there will be some surprises for sure.

**Comment by KosmosisDire** [comment] 2023-12-05 22:20
I will close this for now since the specific issue has been resolved

**Closed by KosmosisDire** 2023-12-05 22:20 UTC
Labels: enhancement
