### ISSUE TITLE
some unrelated search items

### ISSUE THREAD

**Issue by XinYaanZyoy** [KosmosisDire/obsidian-webpage-export#357] opened 2024-02-20 09:54 UTC
**Describe the bug**
searching sometimes results in some unrelated items in the list.

**Operating System**
Ubuntu 22.x

**To Reproduce**
1. export
2. serve
3. search on the site
4. See that there is at least one unrelated item

**Screenshots**
will send if necessary 

### IMPORTANT: Error Log
not relevant ig

**Comment by KosmosisDire** [comment] 2024-02-20 10:21
A screenshot would again be helpful, thanks

**Comment by KosmosisDire** [comment] 2024-02-20 10:22
The search uses fuzzy searching, so it's very likely that the results that show up have a fuzzy match. It is also a full text search not just searching the titles

**Comment by KosmosisDire** [comment] 2024-02-20 10:40
I found your website and I was able to text it. I beleive everything is working as intended. The search method is just different than in obsidian. 

As a side note, tags now work :)

**Comment by XinYaanZyoy** [comment] 2024-02-20 10:54
Oh, okay.

Oh, yes I did see the tags thing, it's fantastic! (I forgot to edit the index page mentioning it haha)

(btw I experienced that downloading upon going back thing, now I am not able to produce It but when i can I'll create an issue)

let me still send the screenshots, and you can confirm if it's fine or not.

**Comment by XinYaanZyoy** [comment] 2024-02-20 10:57
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32465479/c2d45b7b-a2f5-41c2-82e5-efcdaa5d6bae)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32465479/a617991e-2af6-47a1-b81f-537dd4486eb5)

in the "musi" the last one is unrelated, in the "music" the last two are.

**Comment by KosmosisDire** [comment] 2024-02-20 11:08
1. `Musi` is only one letter away from `Musk`
2. `Music` -> `Magic` and `Music` -> `Basic`

Are there files that _should_ be there that aren't? That is the important thing.

**Comment by XinYaanZyoy** [comment] 2024-02-20 11:09
Oh I understand that now, thanks. 

yes, see #356 .

**Comment by KosmosisDire** [comment] 2024-02-21 16:32
Im going to go ahead and close this issue, but leave #356 open.

**Closed by KosmosisDire** 2024-02-21 16:32 UTC
Labels: bug
