### ISSUE TITLE
Export current file + related notes (outgoing links)

### ISSUE THREAD

**Issue by Oskiator** [KosmosisDire/obsidian-webpage-export#59] opened 2023-04-09 19:37 UTC
Hi,

Here is a new idea. I is related to exporting multiple file like suggested [here](https://github.com/KosmosisDire/obsidian-webpage-export/issues/13) but is a different idea.

**Describe the solution you'd like**
I would like to be able to export on file with the notes related to the outoing links. 
So I can share my note with someone who can then navigate on one level. For example my note could contain a concept (let's say the "halo effect" that is defined in another note.  

Hmm I'm wondering if it is the same idea or not that [this one](https://github.com/KosmosisDire/obsidian-webpage-export/issues/38).

It could be really cool. Thanks for this plugin. 🙏

**Comment by KosmosisDire** [comment] 2023-04-10 05:44
Yes this has already been suggested and is planned. Thanks!

I will close this since it is a duplicate of #38

**Closed by KosmosisDire** 2023-04-10 05:44 UTC
Labels: enhancement
