### ISSUE TITLE
Custom callouts don't work

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#75] opened 2023-04-30 10:22 UTC
Custom callouts defined in css snippets or via Admonitions plugin don't work (loose their custom color)

Obsidian:
![image](https://user-images.githubusercontent.com/34401005/235347980-e0eccb4d-e67f-46db-8b15-53cc9d8658a0.png)

![image](https://user-images.githubusercontent.com/34401005/235347990-792251b5-3bc9-4be9-82f9-c547f0c7d433.png)

Export: 
![image](https://user-images.githubusercontent.com/34401005/235347998-ecb413b9-6845-46b3-988f-905f9918f03f.png)

**Comment by KosmosisDire** [comment] 2023-04-30 19:11
Have you selected them in the Custom CSS section? If not that may be a bug with including the custom css in the background renderer. Switching off the background renderer for now will probably fix this.

Thanks for the report

**Comment by dgudim** [comment] 2023-05-01 10:32
Yes, i have indeed selected them in the custom css section. Non-background renderer works fine

**Comment by KosmosisDire** [comment] 2023-05-01 21:57
This should be fixed in version 1.5.1. Thanks for the report!

**Comment by KosmosisDire** [comment] 2023-05-04 03:09
I am not able to reproduce this problem anymore even without enabling the option you mentioned above. I am testing on the development version though so I may have inadvertently fixed it. If this is still not fixed in the next update I will look into it further. I also did not need to include the styles in the Webpage HTML Export thrid party plugin CSS settings.

**Comment by KosmosisDire** [comment] 2023-05-04 04:47
I have released the new version on whch I tested this, so if I inadvertently fixed it you should be able to test it now.

**Comment by KosmosisDire** [comment] 2023-05-05 07:37
Ah okay, so the difference is that I am using this syntax and it works fine:
````
```ad-test
Hello
```
````

I don't think there is any way for me to make the plugin work without writing specific code to support it in the plugin. I'll consider doing that, but for now you can either use the old codeblock systax, or use the snippets option inside admonitions. Thanks!

**Comment by dgudim** [comment] 2023-05-05 08:56
But it was working before the background renderer just fine. But ok, I'll use the css snippet for now

**Comment by KosmosisDire** [comment] 2023-05-05 08:59
Hmm, that is true. I will look into it more

**Comment by jvsteiner** [comment] 2023-05-08 10:46
I don't know if this is related or not, but I can't get any of my custom css snippets to be included in the exported output at all.  In my plugin settings view, I do not see an option to include the users custom css (as configured under the "Appearance" tab rather than through plugins.)  These would usually be located under `vault/.obsidian/snippets/*.css`

**Comment by dgudim** [comment] 2023-05-08 11:12
My css snippets are included normally (as long as they are enabled)

**Comment by jvsteiner** [comment] 2023-05-08 13:18
working now - dunno what happened

**Closed** 2023-05-30 01:54 UTC
Labels: bug

**Comment by KosmosisDire** [comment] 2023-05-30 02:04
Update 1.6.0 added built-in support for the admonitions plugin :)

**Comment by dgudim** [comment] 2023-05-30 16:44
Yaaaay. Still a small issue though (Basically 2nd, 3rd and etc. callouts are not themed and don't have a collapse icon)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/34401005/92fd9e38-d762-44bf-a50e-e34fb1aea98a)

Here is the test file:
```
- 1
>[!tldr]
>   Text

- 2
> [!tldr]
>   Text
```
