### ISSUE TITLE
Linked mentions do nothing when clicked

### ISSUE THREAD

**Issue by dorkerdev** [KosmosisDire/obsidian-webpage-export#61] opened 2023-04-15 15:49 UTC
**Describe the bug**
Linked mentions do nothing when clicked

**Operating System**
Brave on Windows 7 x64

**To Reproduce**
1. Export a page that contains linked mentions to HTML
2. Open HTML and try clicking the linked mentions to navigate to that page
3. Nothing happens when clicked

### IMPORTANT: Error Log
1. Dev console shows no errors when clicking the linked mentions

**Comment by KosmosisDire** [comment] 2023-04-16 04:24
Hello, I assume you mean links to other files, aka a link that was created with this markdown: `[[Other File Name]]`? This is certainly working and I just tested on Brave. Would you mind sharing the HTML file that was generated that has this behavior? A screen recording and the original markdown could be helpful too.

Additionally, you could try testing in another browser and see if that changes anything, let me know.

Thanks for the report!

**Comment by dorkerdev** [comment] 2023-04-16 10:49
I am referring to linked mentions as shown here:

![image](https://user-images.githubusercontent.com/89675012/232299753-2b0fb378-074d-4625-8b08-48d3ef514eda.png)

Attached are two .zip files, one of the source .md and the other of the the exported HTML files from the plugin. I also tried in Firefox and it exhibits the same behavior. When I click on `Test 2` under linked mentions. nothing happens. Clicking on `[[Test 1]]` and `[[Test 2]]` work as expected. It's just the linked mentions that don't work.

[test markup.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/11241977/test.markup.zip)
[test html.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/11241978/test.html.zip)

**Comment by KosmosisDire** [comment] 2023-04-16 20:33
Ah okay, this has already been reported in issue #37. 

Unfortunately, I am not sure this fix will come soon since those links are controlled by an internal obsidian script so it would take a decent amount of work to get them to link up properly. I will fix it eventually, thanks for the report.

I will close this for now as it is a duplicate of #37.

**Closed by KosmosisDire** 2023-04-16 20:33 UTC
Labels: bug
