### ISSUE TITLE
[Bug]: Anchor Links to Callouts not Working

### ISSUE THREAD

**Issue by lvlanson** [KosmosisDire/obsidian-webpage-export#407] opened 2024-03-14 20:20 UTC
### What happened?

I link to callouts through documents, these links don't work in the exported documents

### Reproduction

Create a callout

>[!MyCallout]
> This is my callout displaying some information.
>^mycallout

[[#^mycallout|this is my callout link]]

Export document as HTML. You can also put the link and the callout into two separate documents, but note, you need to change the structure of the link.

Expected Behavior:
Click on the link, the view of the page should focus on the callout, just as it would in obsidian. (Similar behaviour as anchor links)

### Last Working Version

Don't know if it ever did

### Version

1.8.01

### Operating System

Linux Manjaro

### Obsidian Version

1.5.8

### Relevant log output

```yaml
Log:
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: ADMONITIONS_CUSTOM_STYLE_SHEET
[WARNING] 	No existing export metadata found. All files will be exported.
[WARNING] 	No existing search index found. All files will be exported.
[WARNING] 	No existing RSS feed found. All files will be exported.
[INFO] 	Using "qips (quantized inner product search)" header as title because it was H1 at the top of the page
[INFO] 	Using "state space models (ssm)" header as title because it was H1 at the top of the page
[INFO] 	Using "linear differential equations" header as title because it was H1 at the top of the page
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: ADMONITIONS_CUSTOM_STYLE_SHEET
[WARNING] 	No existing export metadata found. All files will be exported.
[WARNING] 	No existing search index found. All files will be exported.
[WARNING] 	No existing RSS feed found. All files will be exported.
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: ADMONITIONS_CUSTOM_STYLE_SHEET
[INFO] 	Using "linear differential equations" header as title because it was H1 at the top of the page
[INFO] 	Using "state space models (ssm)" header as title because it was H1 at the top of the page
[INFO] 	Using "qips (quantized inner product search)" header as title because it was H1 at the top of the page
[INFO] 	No old files to delete
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.01
	makeOfflineCompatible     false
	inlineAssets ------------ true
	includePluginCSS          1 plugins included
	includeSvelteCSS -------- true
	titleProperty             PhD Studies Thomas Davies
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 60em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	allowFoldingHeadings ---- true
	allowFoldingLists         true
	allowResizingSidebars --- true
	logLevel                  warning
	minifyHTML -------------- true
	makeNamesWebStyle         false
	onlyExportModified ------ true
	deleteOldFiles            true
	addThemeToggle ---------- true
	addOutline                true
	addFileNav -------------- true
	addSearchBar              false
	addGraphView ------------ false
	addTitle                  true
	addRSSFeed -------------- true
	siteURL                   https://www.staff.hs-mittweida.de/~davies/intranet/
	authorName -------------- Thomas Davies
	vaultTitle                PhD Studies
	exportPreset ------------ documents
	openAfterExport           true
	graphAttractionForce ---- 1
	graphLinkLength           10
	graphRepulsionForce ----- 150
	graphCentralForce         3
	graphEdgePruning -------- 100
	graphMinNodeSize          3
	graphMaxNodeSize -------- 7
	showDefaultTreeIcons      false
	emojiStyle -------------- Native
	defaultFileIcon           lucide//file
	defaultFolderIcon ------- lucide//folder
	defaultMediaIcon          lucide//file-image
	exportPath -------------- /home/thomas/Documents/HTML_EXPORT
	filesToExport             6


Enabled Plugins:
	Zotero Integration
	Citations
	Obsidian Link Converter
	Admonition
	Extended MathJax
	LanguageTool Integration
	TikZJax
	Execute Code
	Codeblock Customizer
	css snippets
	Icon Shortcodes
	CSS Editor
	Obsidian Git
	Excalidraw
	Advanced Tables
	Duplicate Line
	Latex Suite
	Desmos
	Pandoc Plugin
	Marp Slides
	Webpage HTML Export
```

### Additional Info

Expected behavior is this:
[Screencast from 2024-03-14 21-19-34.webm](https://github.com/KosmosisDire/obsidian-webpage-export/assets/23107929/983d9541-74cf-447d-a371-31021dd1b96a)

If I click on the link on the webpage, nothing happens if the link is linking to the same document, if it is in another document, it redirects to the document, but not the callout box.

**Comment by KosmosisDire** [comment] 2024-03-15 15:25
Hi this is just a block link and so this is a duplicate of #57. So I will close this.

I do plan to implement this in the future, but it is harder than it might seem since obsidian stores block link references internally and not in the markdown or html output (although in your case you have specified a block ID manually so it is shown in markdown). I do hope to get this feature added soon though

**Closed** 2024-03-15 15:25 UTC
Labels: bug

**Comment by lvlanson** [comment] 2024-03-15 15:30
When you link to a block, these IDs are created automatically. I will show you how they are created.

Maybe this helps you on solving this. Please let me know if I can provide any assistance.
[Screencast from 2024-03-15 16-29-42.webm](https://github.com/KosmosisDire/obsidian-webpage-export/assets/23107929/1851c49c-ddb5-464d-81da-efb9c8416ca7)

**Comment by KosmosisDire** [comment] 2024-03-15 15:46
Oh sorry, they are stored in markdown but they are not shown in the generated html in any way (as IDs for example) obsidian stores the references internally for use in reading mode. I believe there was also a case where it wasn't stored in markdown but I don't remember. Either way, what I need is for it to make a difference to the HTML which it does not (unless they have changed it). Either way, I do plan to implement this one way or another, but I haven't looked into it since a while ago.

**Comment by KosmosisDire** [comment] 2024-03-15 15:55
I know, but not in the HTML generated by obsidian in reading mode which is what the plugin interacts with.

**Comment by KosmosisDire** [comment] 2024-03-15 16:08
I believe obsidian already exposes the block links in its metadata cache. The problem is just associating which block of HTML has which ID and then adding that as an HTML id. This may be very difficult or very easy, but I haven't looked into it yet. I also need to make sure that when block links change the other affected files are updated in the export (which should work already theoretically).

But again once I actually start to tackle the problem it will be a lot clearer what the main issues are to find solutions to.
