### ISSUE TITLE
Export fails on Mac and Linux

### ISSUE THREAD

**Issue by alombi** [KosmosisDire/obsidian-webpage-export#10] opened 2023-01-09 15:44 UTC
When trying to export a file (or entire vault), the plugin just open the file in another tab but doesn't create any html file

**Comment by KosmosisDire** [comment] 2023-01-09 17:44
@alombi Can you open the inspector in obsidian with Ctrl + Shift + I, then go to Console, then clear the console, and then try exporting a single file and send a screenshot of the console output? Then can you also take a screenshot of the export settings you are using? Then I can hopefully reproduce whatever is happening, thanks!

**Comment by KosmosisDire** [comment] 2023-01-09 17:47
Additionally, could you try creating a completely new empty vault with no other plugins or themes, and export a single file with this plugin from that vault and see if it works there?

**Comment by alombi** [comment] 2023-01-09 17:59
Sure! Here's the screenshots

<img width="473" alt="Screenshot 2023-01-09 alle 18 58 13" src="https://user-images.githubusercontent.com/62696529/211375520-eae0c4a1-f8eb-4123-91b2-20c3bba18dd3.png">
<img width="553" alt="Screenshot 2023-01-09 alle 18 59 26" src="https://user-images.githubusercontent.com/62696529/211375723-f72c37f9-cbac-4544-b7d3-e871de0fb60b.png">

**Comment by KosmosisDire** [comment] 2023-01-10 18:06
I think I have found the issue and I am working on resolving it, it's unfortunately going to take a little bit. @6days9weeks do you happen to have any special characters in the path to your vault? Like characters with accents or umlauts?

**Comment by alombi** [comment] 2023-01-10 18:16
My vault is in iCloud as well

**Comment by KosmosisDire** [comment] 2023-01-10 18:20
Ah okay, it actually might not not be the special characters but maybe the POSIX file path format that macOS uses (which I didn't account for). The changes I am making should address that as well.

**Comment by tinyg0blin** [comment] 2023-01-10 18:27
> Ah okay, it actually might not not be the special characters but maybe the POSIX file path format that macOS uses (which I didn't account for). The changes I am making should address that as well. 

For what it's worth, I was having the same problem and I'm on Linux (Linux Mint distro)

**Comment by KosmosisDire** [comment] 2023-01-10 18:28
Linux also uses POSIX file paths, so probably the same problem

**Comment by KosmosisDire** [comment] 2023-01-10 18:30
Thanks for all the info guys, and for being patient with a plugin that's totally broken on Mac and Linux 😅

**Comment by KosmosisDire** [comment] 2023-01-17 21:24
I just want to update this issue, and say that it will probably be a while before this is fixed as I have suddenly been swamped by university studies. I still plan to fix this as soon as I can but it may take a while even so. I am of course open to PRs on this issue as well.

**Closed** 2023-02-01 23:55 UTC
Labels: bug, in the works

**Comment by KosmosisDire** [comment] 2023-02-02 03:09
This should be fixed now! Please test this latest release and let me know if it works now! Thanks!

**Comment by tinyg0blin** [comment] 2023-02-02 16:11
> This should be fixed now! Please test this latest release and let me know if it works now! Thanks!

Fix works for me. Very neat stuff !

**Comment by mtuckerb** [comment] 2023-02-03 00:15
This is definitely looking a lot better, but I am having trouble exporting a large vault. a large portion of the rendered pages have no body. I can't figure out what the issue is, but if I individually export the page, it works just fine (over-writing the one created by the vault export).

**Comment by KosmosisDire** [comment] 2023-02-03 00:26
@mtuckerb Interesting, could you first make a separate issue for this? Also since, I don't have any way to reproduce this, would you be willing to send me a zip file of the vault you are trying to export, or if possible a subset of the vault that still causes the problem (You can right click on a folder to export everything in it). Also what OS are you on?

Create a new issue, and include this info there. Thanks!
