### ISSUE TITLE
Internal link to block (section) doesn't work in HTML output (Important!)

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#298] opened 2023-12-08 10:25 UTC
Internal links to block(s) / sections doesn't work in HTML output. (Tested on single note HTML export.)

Unfortunately, even if the internal link to block is created in the HTML output, but the block / section anchor does not, thus the link does nothing.

It would be important to look after because otherwise there is no possibility to make anchor links to specific places other than headings inside the HTML document.

The internal link works only if the anchor link is a heading.

Try reproduce:
Create a note in obsidian,
Create a block identifier ^some_anchor  (name it by yourself or simply)
Create a link to this specific block by suggestion
Convert the note to HTML

![InternalLinkToBlock_doesnt_work_2023-12-08](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/3cee4e46-c1d5-4166-b8ee-b3baaf3e4236)

Operating System
WIN 10 Pro
Obsidian v.1.4.16
your plugin v. 1.7.3

**Comment by KosmosisDire** [comment] 2023-12-08 15:50
I believe this is a duplicate of #57?

**Comment by vgyenge6** [comment] 2023-12-08 16:36
> I believe this is a duplicate of #57?

Yes, this is same issue. Sorry I did not read that.
See: https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note

I'm using this frequently to. (It is similar, as an anchor link in a normal HTML page, and because of the special reference e.g. similar to the mentioned issue in #57 but if the TOP is a heading that will work, but not if that is  block id due to there is not a HTML tag e.g <a name= or id=... or <a data-block= etc. .. or  or any reference in the document to that block id. )
```
<h2 data-heading="TOP" class="heading" id="==TOP"></h2>
<a data-href="#TOP" href="#TOP" class="internal-link" target="_self" rel="noopener">TOP</a>
```
will work well., but not any block id.

Thank you to take into consideration because it is important.

**Comment by vgyenge6** [comment] 2023-12-08 17:01
> I do plan to implement this

Thank you. I understand the reason and possible resolutions you write above .. :) :(

Btw.: What I really do not understand obsidian surely has an inbuilt perhaps html renderer how one can see the md document in 'Reading view'. I do not understand why they did not implement a simple single document 'Export to HTML' feature given inbuilt. 
It is very annoying because most browsers can not render these md files properly since its special markup, and even if the local md file store can be very cleverly maintained and edited in obsidian, there is not any HTML export what one finally can make these files usable on else platforms.
**YOUR PLUGIN IS ESSENTIAL** and very very needed!!!!!

**Comment by KosmosisDire** [comment] 2023-12-08 17:05
Yes, I thought the same thing haha. There is an internal API function to render markdown, but it does not support embeds or most plugins correctly, just basic markdown. I guess the reason they don't let you export HTML is because it would conflict with their Publish service.

**Comment by vgyenge6** [comment] 2023-12-08 17:16
> don't let you export HTML is because it would conflict with their Publish service.

Sure, that may be the reason, but that is a bit stupid but a real business idea, surely for them. But the whole clever software can not count and almost unusable if that can be used or published on their platform only. 
It is my private opinion.

**Comment by KosmosisDire** [comment] 2023-12-08 17:27
> > I do plan to do this in the future, but it may be a little while.
> 
> Please  do releases in smaller steps. if those are possible. Much thanks.

My schedule makes it hard to do smaller steps. I am doing what I can :)

**Comment by vgyenge6** [comment] 2023-12-08 17:35
> I am doing what I can :)

Thank you, I'll be waiting patiently, and I have been doing meanwhile hacking manually in the HTML what I can...but that is a bit really annoying. :(

**Comment by KosmosisDire** [comment] 2023-12-12 19:06
I will go ahead and close this since it's a duplicate, but thank you for your feedback :)

**Closed by KosmosisDire** 2023-12-12 19:06 UTC
Labels: bug
