### ISSUE TITLE
PDF doesn't get embedded

### ISSUE THREAD

**Issue by XinYaanZyoy** [KosmosisDire/obsidian-webpage-export#154] opened 2023-06-28 17:08 UTC
**Describe the bug**
upon export, the pages which have pdfs embedded in the markdown don't get the pdf embedded. also, the pdf files are not getting copied. (just like how images and pasted images do)

**Operating System**
Linux

**To Reproduce**
1. copy a pdf to vault directory
2. create a note with that pdf embedded in it
3. export
4. serve the files, and see that the pdf is not embedded, not only that there's an empty embedded pdf skeleton of obsidian.

**Screenshots**
obsidian note and the HTML webpage
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32465479/ff8036fd-b4a7-4f93-b09f-e043edb7d369)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32465479/1dd6c3ff-cfe8-4fef-aa93-c0463dade743)

### IMPORTANT: Error Log
https://pastebin.com/JkZ9KBWz
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32465479/31dc4e18-f56e-4dfd-b2f6-fda7e0faf74b)

**Comment by KosmosisDire** [comment] 2023-06-28 18:44
This is a duplicate of issue #95 so I will close this.

I will likely revert the pdf viewer to the default one instead of obsidian's custom viewer because their custom viewer uses a lot of custom code that I cannot use.

Thanks for the report!

**Closed by KosmosisDire** 2023-06-28 18:44 UTC
Labels: bug
