### ISSUE TITLE
Title of note isn't carried into html export.

### ISSUE THREAD

**Issue by pitecantropo** [KosmosisDire/obsidian-webpage-export#206] opened 2023-09-12 08:11 UTC
**Describe the bug**
Noticed that when i export a note the title of the note isn't carried into html export, even though the "Add filename as title" is set in the options.

**Operating System**
Windows 10

vault:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/4513487/c0dff787-dc25-438c-8092-54e2707416c4)

html export:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/4513487/e4b28f7b-8083-4b00-a6b9-74478a1e0639)

**Comment by KosmosisDire** [comment] 2023-09-12 15:17
This is a duplicate of #202

**Closed** 2023-09-12 15:18 UTC
Labels: bug
