### ISSUE TITLE
Partially exported files

### ISSUE THREAD

**Issue by Nirvanatin** [KosmosisDire/obsidian-webpage-export#42] opened 2023-02-26 15:28 UTC
I have been exporting documents from one of my repositories, but the exported files are being chopped off and not complete when the document is long.

**Comment by KosmosisDire** [comment] 2023-02-27 05:34
I have noticied this sometimes. Usually I can fix this by exporting the document by itself again or restarting obsidian and exporting it twice. I am not entirely sure what is causing it but it is on my list to fix. Thanks!

**Comment by Nirvanatin** [comment] 2023-02-27 06:25
Thank you for the plugin. This [test markdown](https://peerpad.net/#/r/markdown/9UVYaBkQ9iFx8BDEhj17JGs6i1CuYc3ehY3jNp7iYH9b/4XTTM6n9NtD6ERSW77MkCXb7G47hvifX1gwM1kBGcetKQW6tH) can be used to reproduce the results. This issue may be caused by the triple backticks.

**Comment by KosmosisDire** [comment] 2023-02-27 08:01
Hey, thank you, but this link is blank: 
![image](https://user-images.githubusercontent.com/39423700/221506756-816aab17-de67-406b-87c8-b4b943f13820.png)

**Comment by Nirvanatin** [comment] 2023-03-03 12:07
Sorry for the late reply. 
https://rentry.co/mdtest/raw

**Comment by xllowl** [comment] 2023-03-10 11:32
I found that if the long doc is divided by using links like ![[<note>]], the export works well.

**Comment by KosmosisDire** [comment] 2023-03-10 22:03
Huh, interesting. Maybe this is actually a bug in obsidian. Because I _AM_ telling the API to render the whole document, maybe obsidian just doesn't for some reason but specific elemts make it render that part so it isn't usually a problem

**Comment by xllowl** [comment] 2023-03-11 08:55
> Huh, interesting. Maybe this is actually a bug in obsidian. Because I _AM_ telling the API to render the whole document, maybe obsidian just doesn't for some reason but specific elemts make it render that part so it isn't usually a problem

May not a bug？Since rendering whole document consumes lots of rams. Maybe we can try to increase the rendering time to solve that ?

**Comment by KosmosisDire** [comment] 2023-03-21 16:17
Huh on my computer rendering the long file linked above works fine. You may be right @xllowl, but obsidian is supposed to block until the document is fuly rendered according to the API. Maybe it doesn't actually wait correctly and so it would benefit from a longer wait just in case.

**Comment by Oskiator** [comment] 2023-04-09 19:54
I get this one too. If it is useful, here is the doc (without images) I tried several time to export. 
I made several tries and it is chopped at different part. 
[@BangerterRoulinReussirEntretienEmbauche2012.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/11186205/%40BangerterRoulinReussirEntretienEmbauche2012.md)

**Comment by KosmosisDire** [comment] 2023-04-10 05:46
This is a very elusive problem, I don't think it is caused by any specific content in the documents because exporting the same documents on my end don't cause the problem, but I do run into this problem myself. I am however very aware of it and have made some changes to hopefully fix this that will be in the next release

**Comment by KosmosisDire** [comment] 2023-04-29 10:50
Hey guys, this problem should be fixed in the latest update due to the new background render feature. It in enabled by default in the new update. Thanks for the report and for the information everyone, let me know if you find any other problems! 😊

**Closed by KosmosisDire** 2023-04-29 10:50 UTC
Labels: bug, in the works
