### ISSUE TITLE
Latex equations, Obsidian Callouts, Tables are not rendered properly

### ISSUE THREAD

**Issue by stojan97** [KosmosisDire/obsidian-webpage-export#283] opened 2023-11-21 06:23 UTC
**Describe the bug**
Rendering issues are present after the export to HTML files.

So far I've seen there are issues with Latex rendering, Tables and Obsidian callouts not showing the icons.

**Operating System**
Windows 10 Pro

**To Reproduce**
...

**Screenshots**

## Markdown Tables 

Obsidian:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/10180981/60ad11dd-2b60-4a98-b728-78bce6c2a1ad)

HTML Export:
![Capture1](https://github.com/KosmosisDire/obsidian-webpage-export/assets/10180981/76d3e699-b2f4-4e2b-87a2-54080e4a5a29)

<br />

## Latex rendering

Obsidian:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/10180981/90adadd4-5300-4f19-9357-4d2937db1bf4)

HTML Export:
![Capture](https://github.com/KosmosisDire/obsidian-webpage-export/assets/10180981/d4a8e1d8-7950-42e9-a3b3-dbfb04697743)

<br />

## Obsidian Callouts

Obsidian:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/10180981/eef22949-ba7a-41eb-b13f-c3449ca210f9)

HTML Export:
![Capture2](https://github.com/KosmosisDire/obsidian-webpage-export/assets/10180981/36c60cbc-0ffc-4c57-9136-c70a89eb150c)

### IMPORTANT: Error Log
No errors in Browser Console .

**Comment by KosmosisDire** [comment] 2023-11-21 07:44
Thank you, the callouts will be fixed in the next update. I believe the latex problem will also be fixed in the next update. One other person has reported the table issue, but I have never been able to reproduce it. Does this issue occur in all browsers? Thanks.

**Comment by stojan97** [comment] 2023-11-21 17:46
It seems to happen on multiple browsers (Google Chrome, MS Edge).

I tried checking whether is the Latex in the Tables, but it's not, it happens every time for any table

**Comment by KosmosisDire** [comment] 2023-11-21 19:00
What theme are you using?

**Comment by stojan97** [comment] 2023-11-25 07:03
Github Theme

**Comment by KosmosisDire** [comment] 2023-11-29 23:21
I found the issues with the tables, so all three of these items will be fixed in the next update

**Comment by stojan97** [comment] 2023-11-29 23:27
Also, one question: Is there a way to have the same width of the note as in obsidian because the default is not the same.

**Comment by KosmosisDire** [comment] 2023-11-29 23:34
This is something I tried to implement a while back and ended up just setting a default value and letting the user change it (you can modify the width in the settings which I am sure you saw). 

But this is something I will implement again in the future, it's just a little complicated to get the width because the width is defined in css and isn't always static. It often uses a calc property, or is defined as a different variable name in different themes. This is why I originally did not implement it. But again I would like to get it working reliably.

If you'd like to create a new issue for that it will be easier to track progress on that feature specifically. Thanks again :)

**Comment by KosmosisDire** [comment] 2023-12-01 20:35
I am quite busy so I can't give a specific time. I would probably expect it over the holidays some time

**Comment by KosmosisDire** [comment] 2024-02-20 08:05
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:05 UTC
Labels: bug, approved, implemented
