### ISSUE TITLE
Bold on H1 in 1.8.0-2b isn't supported

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#330] opened 2024-01-30 16:00 UTC
**Describe the bug**
If I embolden the H1 title at the beginning of my docs, export throws warnings, adds a second duplicate H1. (Presumably from the filename?)

**Operating System**
Fedora Linux

**To Reproduce**
1. Create H1 at beginning of doc.
2. Mark it bold, e.g., `# **Bold Heading**`
3. It looks fine (works) in obsidian.
4. Export.

### IMPORTANT: Error Log
![things](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/46090ee3-c203-49bf-80d0-0b090db1afef)

**Comment by KosmosisDire** [comment] 2024-01-31 19:58
Thanks, this is definetly a bug but I know what the problem is. I will get a fix out for this

**Comment by KosmosisDire** [comment] 2024-02-02 01:32
Test this on 1.8.0-3b and let me know how it works

**Comment by KosmosisDire** [comment] 2024-02-02 06:56
Hey, could you try this again on 1.8.0-4b? Thanks!

**Comment by ryran** [comment] 2024-02-02 13:09
> Hey, could you try this again on 1.8.0-4b? Thanks!

Using 1.8.0-7b:
- the new issue from my previous comment is resolved
- the original issue with bold H1 throwing warnings and triggering a duplicate H1 has returned

**Comment by KosmosisDire** [comment] 2024-02-03 09:41
Try this again in 1.8.0-8b

**Comment by ryran** [comment] 2024-02-03 17:35
> Try this again in 1.8.0-8b

Starting with 1.8.0-8b, it seems my theme's font faces & styling are no longer respected. Now, my H1 headings always look bold (when exported). That said, after adding bold to an H1, export no longer throws warnings and no longer adds an extra H1, so that particular issue seems fixed. :smile: 

I really need to learn how to use CSS to modify theme styling... that would be much better for me than explicitly marking headings as bold. Sigh.

**Comment by KosmosisDire** [comment] 2024-02-03 18:50
Could you show an example of what it looks like in obsidian vs in the export and point out the differences? Are you still using the everforest theme?

**Comment by KosmosisDire** [comment] 2024-02-03 18:51
If you want all your headers to be bold, it's pretty easy. I would recommend doing some googling or asking on the obsidian discord server. They have a channel specifically for asking about snippets and theming

**Comment by KosmosisDire** [comment] 2024-02-03 19:23
I think it is likely that the reason our H1 headings are always bold is because the plugin is creating an inline title from them. Obsidian (and your theme) have different styles for the inline title, and your theme probably sets them to bold. So I think it is working as expected. I suppose I could make it not apply inline title styles to the top header and leave it as a plain H1, but I thought it might be nice to give it the inline title styles.

**Comment by ryran** [comment] 2024-02-03 21:21
> Could you show an example of what it looks like in obsidian vs in the export and point out the differences? Are you still using the everforest theme?

Yep same theme, with no custom css. Here's what it looks like in obsidian:
![obsidian](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/50492c78-243b-4680-91e8-7a450326e38f)

And here's a screenshot of the current b19.org, which was generated from that (i.e., no bold H1) with v1.8.0-8b:
![live](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/aad046b1-ff4c-46ad-b8b2-f3ec8f0676fe)

It's not only automatically bold now, but it's a completely different font face.

> If you want all your headers to be bold, it's pretty easy. I would recommend doing some googling or asking on the obsidian discord server. They have a channel specifically for asking about snippets and theming

Yeah I'm on there and have been trying to figure out what the best place to ask is. I'll keep looking.

> Obsidian (and your theme) have different styles for the inline title, and your theme probably sets them to bold. So I think it is working as expected.

I don't think that's true, based on what I see in the above screenshots, but /shrug

**Comment by KosmosisDire** [comment] 2024-02-03 22:05
Well normally the first header in obsidian is not an inline header. But the plugin is taking the first header and converting it into one. That's why it's styled differently. The inline title can also have a different font face too

**Comment by KosmosisDire** [comment] 2024-02-03 23:52
I will change it so the header has the same styles as any normal h1 header would. I think that is better anyway as it gives users what they expect more often

**Comment by KosmosisDire** [comment] 2024-02-05 01:08
I made top headers have the same style as normal headers in 1.8.0-9b. Let me know if this feels better

**Comment by ryran** [comment] 2024-02-05 03:53
> Well normally the first header in obsidian is not an inline header. But the plugin is taking the first header and converting it into one. That's why it's styled differently. The inline title can also have a different font face too
> 
> I will change it so the header has the same styles as any normal h1 header would. I think that is better anyway as it gives users what they expect more often
>
> I made top headers have the same style as normal headers in 1.8.0-9b. Let me know if this feels better

Honestly I don't quite understand your explanation, but I'm OK with that. In 9b, the H1 font face now matches what I see in the obsidian reading view ... unless I embolden the H1 -- then the reading view renders it bold, but exporting with your plugin doesn't. (However, this doesn't throw any warnings or cause any problems and I've already decided I'd rather style all my H2 & H2 headings bold via CSS, so I'll let it be.)

**Comment by KosmosisDire** [comment] 2024-02-05 04:54
Obsidian has a concept of an inline header which you can enable in the settings. This automatically shows the file's title as the first header in the document. This is the inline title and it can be styled seperately from all other headers.

**Comment by KosmosisDire** [comment] 2024-02-05 04:55
I will leave this issue open to remind myself to look back at it since the plugin _should_ still be taking styles from the one in obsidian correctly.

**Comment by ryran** [comment] 2024-02-05 16:12
> Obsidian has a concept of an inline header which you can enable in the settings. This automatically shows the file's title as the first header in the document. This is the inline title and it can be styled seperately from all other headers.

Ohhh... hmmm.
That reminds me that for clarity I probably should have shared the way I'm doing it is I have an explicit `# doc title here` at the beginning of my markdown docs (in addition to yaml frontmatter) and I have the "inline title" option disabled, i.e.:
![inline-title](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/7ecc3941-8256-4736-8ad6-adaaf9b886f7)

**Comment by KosmosisDire** [comment] 2024-02-05 16:43
Yeah I figured you had it disabled. The plugin supports either way

**Comment by KosmosisDire** [comment] 2024-02-20 08:31
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:31 UTC
Labels: bug
