### ISSUE TITLE
Full page is not produced

### ISSUE THREAD

**Issue by TohidN** [KosmosisDire/obsidian-webpage-export#189] opened 2023-09-10 14:54 UTC
# **The bug**
Any content with more that a few paragraphs won't be completely generated in HTML format, missing most parts of page content after a few paragraphs of text.

# **Version**
Obsidian 1.4.5 on windows, plugin version 1.6.0
I've tried disabling all my plugins, creating a new vault with only this plugin, disabling recent obsidian features, and trying different plugin configurations. Nothing works.

# **To Reproduce**
Given this markdown content:
```md
First Section: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

---
Second Section:
- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

---
Third section
```
`Third section` and anything after that are not rendered. However if we shorten the length of the text in list items(starting with `Lorem ipsum`) in `Second section` it will render html correctly.

Another example:
```md
# First header
1. Ordered list 1.
2. Ordered list 2.
3. Ordered list 3.
	- Unordered list 1
	- Unordered list 2
	- Unordered list 3
	- Unordered list 4
	- Unordered list 5
	- Unordered list 6

# Second header
Second section: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Third header
Third section: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
In this example the content of  `Third header` and anything after that won't be rendered in html. however if we remove the line for `Unordered list 6` or shorten the length of `Second section: Lorem ipsum ...`, the content of `Third header' will be rendered. both examples suggest variable length issues.

**Comment by I2rys** [comment] 2023-09-10 15:04
The issue is related to #183 and I think this can be label as duplicate.

**Comment by KosmosisDire** [comment] 2023-09-10 16:42
Yes thank you this is a duplicate and as such I will close this

**Closed** 2023-09-10 16:43 UTC
Labels: bug
