### ISSUE TITLE
[Bug]: Input fields for export path broken

### ISSUE THREAD

**Issue by AlixO1** [KosmosisDire/obsidian-webpage-export#471] opened 2024-07-08 16:07 UTC
### What happened?

same issue as user here -https://github.com/KosmosisDire/obsidian-webpage-export/issues/367

When trying to export the popup to configure it is empty 
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/127955003/83aace5b-0b64-41f3-9a26-f6119921a282)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/127955003/acef4f94-d2ea-4d9b-bf37-c8bb20fa0907)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/127955003/b260a910-83c8-4f1c-8a5d-7503ce2d4391)

### Reproduction

whenever I try to export the page this occurs

### Last Working Version

First time using plugin

### Version

1.8.01

### Operating System

Windows 10

### Obsidian Version

1.6.5

### Relevant log output

```yaml
Log:
[INFO] 	Including stylesheet: css-settings-manager


Settings:
	settingsVersion --------- 1.8.01
	makeOfflineCompatible     true
	inlineAssets ------------ false
	includePluginCSS          2 plugins included
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	allowFoldingHeadings ---- true
	allowFoldingLists         true
	allowResizingSidebars --- true
	logLevel                  warning
	minifyHTML -------------- true
	makeNamesWebStyle         true
	onlyExportModified ------ true
	deleteOldFiles            true
	addThemeToggle ---------- true
	addOutline                true
	addFileNav -------------- true
	addSearchBar              true
	addGraphView ------------ true
	addTitle                  true
	addRSSFeed -------------- true
	siteURL                   https://alixo22.sg-host.com/
	authorName -------------- Alix
	vaultTitle                Obsidian Vault
	exportPreset ------------ website
	openAfterExport           false
	graphAttractionForce ---- 1
	graphLinkLength           10
	graphRepulsionForce ----- 150
	graphCentralForce         3
	graphEdgePruning -------- 100
	graphMinNodeSize          3
	graphMaxNodeSize -------- 7
	showDefaultTreeIcons      false
	emojiStyle -------------- Native
	defaultFileIcon           lucide//file
	defaultFolderIcon ------- lucide//folder
	defaultMediaIcon          lucide//file-image
	exportPath --------------
	filesToExport             0


Enabled Plugins:
	MAKE.md
	Timelines
	Map View
	Style Settings
	Supercharged Links
	Templater
	Text Format
	Find and replace in selection
	Webpage HTML Export
```

**Comment by KosmosisDire** [comment] 2024-07-08 16:12
Hi, as you said this issue is already being tracked in #367, and has been fixed in the beta version already, so I will go ahead and close this. I cannot remember if the fix for this has been released yet, but the issue is that you are using the `title` frontmatter field, but the type of the field is set to a number. So convert any title number fields to strings and that should fix it until you can access the new version.
Thanks!

**Closed by KosmosisDire** 2024-07-08 16:12 UTC
Labels: bug

**Comment by AlixO1** [comment] 2024-07-08 16:20
> Hi, as you said this issue is already being tracked in #367, and has been fixed in the beta version already, so I will go ahead and close this. I cannot remember if the fix for this has been released yet, but the issue is that you are using the `title` frontmatter field, but the type of the field is set to a number. So convert any title number fields to strings and that should fix it until you can access the new version. Let me know if you have any questions. Thanks!

Thanks for the quick reply, I really appreciate it. I'm quite new to Obsidian, are you able to give me some pointers on how i'd go about this? Is it as simple as just changing the titles to not have any numbers?

**Comment by KosmosisDire** [comment] 2024-07-08 17:16
Here is the obsidian help page about properties: https://help.obsidian.md/Editing+and+formatting/Properties
Properties allow you to add metadata about a file. This is data that isn't actually the note content but rather data about the note itself. This can be used to set an alternate title for the note which shows up in exports (but not in obsidian). Somewhere in your vault there is probably a property called title but it is set to a number instead of text. Are you the one who created the vault you are using?

**Comment by KosmosisDire** [comment] 2024-07-08 17:17
Also, you can try exporting using the beta version (there are instructions to install the beta version in the readme). I might've fixed it there.

**Comment by AlixO1** [comment] 2024-07-10 09:57
> Here is the obsidian help page about properties: https://help.obsidian.md/Editing+and+formatting/Properties Properties allow you to add metadata about a file. This is data that isn't actually the note content but rather data about the note itself. This can be used to set an alternate title for the note which shows up in exports (but not in obsidian). Somewhere in your vault there is probably a property called title but it is set to a number instead of text. Are you the one who created the vault you are using?

Thanks for the help mate. the Vault is all mine however it is a bit of a mess at the moment, i picked up obsidian at the start of the year and have been constantly changing the structure and templates of my notes so ill take this as a sign I need to tidy things up.

I've created a secondary vault to use your plugin with for now until I get it working on my main vault. Thanks for creating such a handy plugin, i've been looking for a way to easily share notes with my friends while keeping the style of my notes intact.
