### ISSUE TITLE
The problem with displaying syntax highlighting on the page

### ISSUE THREAD

**Issue by aivx** [KosmosisDire/obsidian-webpage-export#372] opened 2024-02-23 09:33 UTC
**Describe the bug**
in version 1.8.0, the html page does not display the syntax highlighting of the code, the "copy" button has also lost styles

**Operating System**
Manjaro Linux (on Windows as well)

**To Reproduce**
1. Export as HTML
2. selecting the .md file
3. choice: HTML Documents or Online web server
4. Export

**Screenshots**
display.html file
![Снимок экрана от 2024-02-23 12-23-38](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/e1d1ff2b-4b37-4673-8ce7-d877c0c021dc)

displaying the .md file
![Снимок экрана от 2024-02-23 12-23-18](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/7c82d742-847e-4dd0-bde0-2244a62c33d9)

General view
![Снимок экрана от 2024-02-23 12-28-07](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/af4c4b98-b0e8-4b0d-9226-26d6b413e19e)

### IMPORTANT: Error Log
plugin:webpage-html-export:71136 [WARNING]   Creating an RSS feed requires a site url to be set in the export settings.
plugin:webpage-html-export:71136 [WARNING]   No existing export metadata found. All files will be exported.
plugin:webpage-html-export:71136 [WARNING]   No existing search index found. All files will be exported.
plugin:webpage-html-export:71136 [WARNING]   No existing RSS feed found. All files will be exported.
plugin:webpage-html-export:68947 Creating website with files:  
[t]
plugin:webpage-html-export:68975 Website created:  
Website {webpages: Array(1), dependencies: Array(14), downloads: Array(15), batchFiles: Array(1), progress: 1, …}

**Comment by aivx** [comment] 2024-02-23 10:39
Export to HTML Documents:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/2cf2b065-8e0b-4a61-b1ea-ac29a1dbabac)

opening a local file in the browser:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/b96abb2a-e1c0-484b-b67a-9ed50efc48e6)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/fc08bdc7-5cb2-40fe-b39d-62c1e8d4413f)

or by running a local server:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/18f92842-42a5-463b-8384-5bb238d4ddd5)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/fd722f6e-dd16-4ddc-a5ea-e259111f06d1)

exported files:
[webpages.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/14384268/webpages.zip)

**Comment by aivx** [comment] 2024-02-23 10:53
Extension Settings:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/580f85c9-aa33-4453-aee9-9c67230b8683)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/3d1fb91c-7710-4447-a68f-ff39e6a98393)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/6ff7e462-12cf-4845-98e2-ae136cdc7744)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/3f09933f-6e30-4ba2-b45f-b765c6404366)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/7e079179-a2f1-41c3-adee-065cde149477)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/26520901/a87532e6-2dcc-4976-a657-1c9410e5f209)

**Comment by KosmosisDire** [comment] 2024-02-23 19:51
Thanks, it looks like it just isn't including some css correctly. I'll see if I can reproduce it given your setup

**Comment by KosmosisDire** [comment] 2024-03-01 10:35
Can you please test out the new beta 1.8.1-0b and let me know if this fixes the issue? Please also let me know if you find any new issues. Thanks!

**Comment by KosmosisDire** [comment] 2024-03-06 10:02
I am closing this since I fixed this issue in a stable release patch

**Closed by KosmosisDire** 2024-03-06 10:02 UTC
Labels: bug
