### ISSUE TITLE
Graph in sidebar does not load on Firefox, works on Chrome

### ISSUE THREAD

**Issue by Nathan-Yorio** [KosmosisDire/obsidian-webpage-export#219] opened 2023-09-13 12:43 UTC
**Describe the bug**
Description is in the title

**Operating System**
Tried it on Linux and my work Mac

**To Reproduce**
- open graph sidebar, see no graph

**Screenshots**
Failed load in firefox
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/108815016/6c2d9821-f0db-40d7-bec1-4b0365d0c080)

Here's how it is in chrome
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/108815016/671fe2e5-84c7-4697-b9b7-4ff92ec0c40d)

### IMPORTANT: Error Log
- When I load up the page in Firefox I get one warning on the wasm js like so:

- path to the erroring js
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/108815016/5688bfd1-8b69-4f85-aac1-eb8914d3033b)

```
Uncaught (in promise) DOMException: Document.querySelector: '.sidebar:has(#graph-canvas)' is not a valid selector
```

- additionally if it means anything for you. I'm serving these up as static assets through hugo and github pages

**Comment by KosmosisDire** [comment] 2023-09-13 15:16
Hi, is your Firefox up to date? That error is caused by an out of date browser most of the time.

**Comment by KosmosisDire** [comment] 2023-09-13 15:22
Hmm actually I am able to reproduce this, apparently Firefox does not yet support the has selector which I was not aware of. I will have to fix this in an update. Thanks for reporting this.

**Comment by KosmosisDire** [comment] 2023-09-13 17:00
This is fixed in v1.7.3 :)

**Closed by KosmosisDire** 2023-09-13 17:00 UTC
Labels: bug, approved, reproduced

**Comment by Nathan-Yorio** [comment] 2023-09-13 17:42
> Hmm actually I am able to reproduce this, apparently Firefox does not yet support the has selector which I was not aware of. I will have to fix this in an update. Thanks for reporting this.

No no, thank you for being so on top of your github issues and making this extension in the first place :)

**Comment by connect-m** [comment] 2023-11-13 20:40
Same problem here for SAFARI version 17.0. 
Chrome works though. :-/

**Comment by KosmosisDire** [comment] 2023-11-13 21:54
@connect-m What version of the plugin are you using? Have you updated to 1.7.3?

**Comment by connect-m** [comment] 2023-11-14 17:00
Yes, I updated via Obsidian and it reads 1.7.3. 
Any ideas how I can help to narrow this down?

**Comment by KosmosisDire** [comment] 2023-11-14 18:22
@connect-m Can you take a sscreenshot of the developer log inside of Firefox? Just press Ctrl-Shift-I to open the inspector and make sure the "Console" tab is selected.

**Comment by connect-m** [comment] 2023-11-14 21:01
Please note: The graph error only occurs in SAFARI. FF like Chrome works fine.

**SAFARI Log:**

![Safari Version 17 0 (18616 1 27 111 22, 18616)](https://github.com/KosmosisDire/obsidian-webpage-export/assets/6062243/a90caf9f-0314-41f6-9e60-785ccdd6864e)


**The FF console reads:**

_wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type '' expected 'application/wasm' [graph_wasm.js:1:6144](https://www.panografico.de/service/ki/lib/scripts/graph_wasm.js)
falling back to ArrayBuffer instantiation [graph_wasm.js:1:6182](https://www.panografico.de/service/ki/lib/scripts/graph_wasm.js)
WebGL context was lost. [index.mjs:3:36](https://cdnjs.cloudflare.com/ajax/packages/constants/lib/index.mjs)
Module Ready [graph_view.js:1:7766](https://www.panografico.de/service/ki/lib/scripts/graph_view.js)
Init called [graph_wasm.js:1:6885](https://www.panografico.de/service/ki/lib/scripts/graph_wasm.js)
Error: SyntaxError: Document.querySelector: '.sidebar:has(#graph-canvas)' is not a valid selector

Using fallback. [graph_view.js:1:3870](https://www.panografico.de/service/ki/lib/scripts/graph_view.js)
WebGL context was lost._

**Comment by KosmosisDire** [comment] 2023-11-14 21:06
Ah my bad I misread because the topic of this issue was Firefox. In that case, if you could create a new issue for this and copy all the info you've given me so far into it that would be amazing.

This is a very odd error, I will look into it and update you on the new issue.
