### ISSUE TITLE
Export doesn't work anymore

### ISSUE THREAD

**Issue by Oskiator** [KosmosisDire/obsidian-webpage-export#239] opened 2023-09-21 20:03 UTC
Hello 👋

**Describe the bug**
- Commands disappeared, only "export website using previsously selected files and settings appears in command panel".
- This command doesn't work, showing the following error in the console
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/96892939/3d1cc206-2a0f-449f-a6eb-4e32c1eb5e31)

**Operating System**
Windows 10

**To Reproduce**
1. Export a note with "export website using previsously selected files and settings appears in command panel"
2. Note doesn't export and the export windows "Generating HTML" doesn't load.

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/96892939/6598450e-543e-400d-8789-b57b12c085b7)

Thanks for your work. I'm looking forward to use your plugin again 🙏

**Comment by KosmosisDire** [comment] 2023-09-21 21:13
Hi, thank you. This is a duplicate of #226, and will be fixed in the next update. I will close this in favor of the other issue

**Closed by KosmosisDire** 2023-09-21 21:13 UTC
Labels: bug
