### ISSUE TITLE
Is it expected that v1.8.0-1b should no longer respect theme colors on export?

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#325] opened 2024-01-29 05:31 UTC
**Describe the bug**
Theme colors are respected in [v1.7.3](https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.7.3) but not all of them are respected in [v1.8.0-1b](https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.8.0-1b).

Aside: except for that issue, I'm loving this beta release (my first) compared to v1.7.3.

**Operating System**
Fedora Linux

**Screenshots**
Instead of screenshots, you can just compare https://b19.org (v1.7.3) with https://b19.org/testjunk (v1.8.0-1b)

### IMPORTANT: Error Log
![console](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/98283ab0-f0b6-48a7-a6b8-8cf9043da934)

**Comment by KosmosisDire** [comment] 2024-01-29 05:35
This is not expected but it seems the problem is just that the body classes have not been copied correctly. Can you try doing the export a second time and see if that fixes it? I will try and track down the source of that bug because I beleive I have experienced it too a few times. In my experience re-exporting always fixed it.

**Comment by KosmosisDire** [comment] 2024-01-29 05:38
(To make re exporting faster you can enable the "Only Export Modified" under the experimental section)

**Comment by ryran** [comment] 2024-01-29 05:41
> This is not expected but it seems the problem is just that the body classes have not been copied correctly. Can you try doing the export a second time and see if that fixes it? I will try and track down the source of that bug because I beleive I have experienced it too a few times. In my experience re-exporting always fixed it.

Hey Nathan! Thanks for the reply! No, this doesn't seem to make a difference. I've done the export 5 times and it's always the same, i.e.:
* none of the header colors come through (H1, H2, etc)
* the link color doesn't come through for dark colorscheme (goes back to standard purple) but DOES come through for light

**Comment by KosmosisDire** [comment] 2024-01-29 05:43
Where are the header colors and link colors defined? Is that from Style Settings? Or are those custom snippets?

**Comment by ryran** [comment] 2024-01-29 05:46
> Where are the header colors and link colors defined? Is that from Style Settings? Or are those custom snippets?

No custom snippets, no style settings plugin. Just the [Everforest theme](https://github.com/0xGlitchbyte/obsidian_everforest).

**Comment by KosmosisDire** [comment] 2024-01-29 05:49
Hmm okay, I'll check it out, I can only assume that the theme is accidentally being loaded before the obsidian themes, so a lot of them get overwritten

**Comment by KosmosisDire** [comment] 2024-01-29 05:51
Actually that's not true. But I will look into it and get that fixed. Are the headers and links colors the only things that are not correct?

**Comment by ryran** [comment] 2024-01-29 05:56
> Actually that's not true. But I will look into it and get that fixed. Are the headers and links colors the only things that are not correct?

It seems the font faces aren't being respected either. Example:
![comparison](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/f6a2e027-5834-410f-bcd5-065371e3d825)

I like that the heading collapse buttons are no longer always visible with the new output... I assume that was a bugfix because the beta brings that more in step with what Obsidian itself shows.

**Comment by KosmosisDire** [comment] 2024-01-29 05:58
Hmm yes I see that, I am also able to reproduce these exact same problems using this theme on my own vault. Yes the collapse buttons were a bugfix, not only with them being visible before but also being weirdly offset lol

**Comment by KosmosisDire** [comment] 2024-01-29 09:44
This should be fixed in 1.8.0-2b

**Closed** 2024-01-29 16:00 UTC
Labels: bug
