### ISSUE TITLE
Mathjax fonts and symbols not as expected

### ISSUE THREAD

**Issue by dromeldar** [KosmosisDire/obsidian-webpage-export#105] opened 2023-05-12 13:10 UTC
**Describe the bug**
When using webpage export on my maths notes, the font and symbol sets in my browser are not displayed as intended (i.e. wrong font etc).
I am using mathjax extended together with a `preamble.sty` which is attached below. However there seem to be no problems with the  preamble, the error persists even when commenting out the complete preamble.
 

**Operating System**
MacOS 12.6.5

**To Reproduce**
1. Write some maths (e.g. `$\mathcal D \simeq \mathbb R \int_{-\infty}^k \hat\phi' $`) 
2. export using webpage export
3. open in firefox (Brave is even worse)
4. observe difference between displayed mathjax in obsidian and browser

**Screenshots**

below Obsidian view:
![Obsidian view](https://github.com/KosmosisDire/obsidian-webpage-export/assets/115623614/a8566df1-d802-4607-97ce-2bb33ec34379)

below Firefox view:
![Firefox view](https://github.com/KosmosisDire/obsidian-webpage-export/assets/115623614/8fe07aaf-a9d2-427e-903e-b63906ab76fd)

below Brave view:
<img width="158" alt="Brave view" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/115623614/eb2f9a43-d7d5-4049-9a55-d3a6151f292a">

**Attachements:**

Preamble:
[preamble.sty.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/11464277/preamble.sty.zip)

**Comment by KosmosisDire** [comment] 2023-05-12 21:30
Okay, I was under the impression before that you were using a custom font in your preamble. If this problem is independent of the preamble, then it is very likely just a duplicate of issues #81 and #102 which I am currently working on fixing. Thank you for the report though!

**Closed** 2023-05-30 01:54 UTC
Labels: bug

**Comment by KosmosisDire** [comment] 2023-05-30 02:00
This is fixed in update 1.6.0, let me know if you have any more problems! And thanks for the report :)
