### ISSUE TITLE
some attached files don't seem to get exported - no resource found for the given identifier

### ISSUE THREAD

**Issue by planefun2** [KosmosisDire/obsidian-webpage-export#179] opened 2023-08-20 16:19 UTC
**Describe the bug**
Trying to export an entire vault to HTML, with images and attachments, which include .mp4 files.

When I export, it seems many images and mp4s which are in the vault are not linked right or not exported correctly and inaccessible on the page. I've tried this a number of times, including in a brand new vault with no other plugins, and the result is the same. 

**Operating System**
Windows 11
Obsidian 1.3.7
Webpage HTML export 1.6.0

**To Reproduce**

There are no errors displayed in the UI following the export, only in the console.

**Screenshots**

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/96006f67-fd32-47eb-ac2a-968aa38e198b)

Here's an example where the file is there in the vault - 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/f33eb201-75b5-479b-be1e-7433c3d0a2f7)

App settings:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/0e94f963-ee5e-4529-a681-33255d117cc2)

### IMPORTANT: Error Log

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/60df5e42-2be6-411f-ad94-9932ecf1c036)

Here's an example - 

app://2d1f77bdb86998e863591ef965a18f6e7e1e/C:/Users/#####/OneDrive - ####/Documents/Obsidian notes/#### #### Cycle/#### #### Cycle/Tuesday, August 22nd, 2023/##/###/attachments/Pasted image 20230810001819.png?1691641099742

**Comment by KosmosisDire** [comment] 2023-08-20 19:05
Hi can you also show how it isn't working on the export?

**Comment by planefun2** [comment] 2023-08-20 22:58
Hi @KosmosisDire - some files are indeed missing altogether from the export - in this example, the file was not exported to the 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/26927e9c-2d75-4d75-85f2-ddabaf253fa3)

Another example - 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/625c328c-e0aa-440d-b18d-54c3e6092cfb)


It appears there might be something wrong with the links in some cases also, as even copying the files directly to the location where they are supposedly referenced doesn't work right.

Comparing the URL, I see that the one I get from navigating to the file directly from the browser after copying it to the supposed-referenced location is different than the one actually referenced - 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/101938798/0627efab-5ebd-4761-af22-7536bd1eaa9e)

**Comment by planefun2** [comment] 2023-08-20 23:01
Things I've tried so far, none of which helped:

- new vault containing just the specific directories I want to export to HTML
- changing themes
- disabling / uninstalling all other plugins
- using a plugin to rename all attachments

**Comment by KosmosisDire** [comment] 2023-08-20 23:05
Hmm, can you try disabling web-style names in the export settings?

**Comment by planefun2** [comment] 2023-08-21 00:15
Yes, tried that too on the latest export in the examples above, but no difference.

**Comment by KosmosisDire** [comment] 2023-08-21 18:02
Huh, I am not able to reproduce this at all. I have a hunch I might have something to do with the path, can you try creating a sandbox vault and exporting to a very simple path, like C:/test/ or something?

**Comment by planefun2** [comment] 2023-08-22 05:54
I tried putting it in a folder called HTML at the root C; and it does the same thing.

**Comment by KosmosisDire** [comment] 2023-08-23 00:35
Hmm, I will look into this more later but for now I am not able to reproduce. Thank you for reporting this though and for all the helpful information

**Comment by planefun2** [comment] 2023-09-15 20:31
Update - I found that the issue seems to be with the wikilinks themelves - copying the vault and opening it from another location results in some random images being pointed to the wrong location, even without exporting.

**Comment by KosmosisDire** [comment] 2024-02-20 08:32
Okay so to clarify this wasn't a problem with the plugin, or it was? It sounds like this can be closed so I will close it, but feel free to reopen if needed. Also if it was a problem with the plugin try exporting again using version 1.8.0

**Closed by KosmosisDire** 2024-02-20 08:32 UTC
Labels: bug, can't reproduce
