### ISSUE TITLE
PDF embedding does not work in all cases

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#362] opened 2024-02-21 11:26 UTC
This feature has been added in 1.8.0! :)
(PDF's do not support specific pages though, this isn't possible with the default html PDF viewer)
If you find any issues please create a new issue
Thanks!

_Originally posted by @KosmosisDire in https://github.com/KosmosisDire/obsidian-webpage-export/issues/291#issuecomment-1953690274_

**Comment by vgyenge6** [comment] 2024-02-21 11:30
Hi,
embed;

- other notes works (**however there is inconsistency in the main TOC if an embedded note has headings**)
- full PDF even yet doesn't work
- embed section works

![Embed_note_PDF_section](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/8a0b5b31-c305-411c-b113-20310289707c)


Thanks for looking after.

**Comment by KosmosisDire** [comment] 2024-02-21 15:04
Hi this is probably a duplicate of issue #346. I am working on it

**Comment by KosmosisDire** [comment] 2024-02-21 15:07
I'll look into the problem with the heading levels

**Comment by vgyenge6** [comment] 2024-02-21 16:16
Hi

> Hi this is probably a duplicate of issue #346.
Yes, I looked into that issue, that may be the problem.

Btw: Regarding this, in this new version 1.8.0 if I rename the exported .html file with contained TOC any of the references in the newly renamed file won't work. Perhaps this is also because of this. However, I did not experience this in the earlier version.

> I'll look into the problem with the heading levels

Thank you. 

Btw: This new version is a nice and big work 🥇

**Comment by KosmosisDire** [comment] 2024-02-21 16:21
> if I rename the exported .html file with contained TOC any of the references in the newly renamed file won't work. Perhaps this is also because of this. However, I did not experience this in the earlier version.

Can you create a seperate issue for this, doesn't sound like it is the same cause.

**Comment by KosmosisDire** [comment] 2024-03-04 03:16
@vgyenge6 Has this issue been fixed in the betas?

**Comment by vgyenge6** [comment] 2024-03-04 08:07
Thank you! I will try this release and come back to react.

**Comment by vgyenge6** [comment] 2024-03-04 09:50
Hi,

The PDF file(s) have not yet appeared for me in this 1.8.1.2b release either however, the PDF viewer does appear not crashing as it was in the previous version. See the two screenshots. 

The first was taken when 1.8.0 was released 
![Embed_note_PDF_section_1 8 0](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/c9d7c5bc-68e0-4e74-86bd-a54865db8648)

the second now 1.8.1.2b.
![Embed_note_PDF_section_1 8 1 2b](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/f20d0ad9-2cd7-48c9-8965-230a828eaaa6)


The main TOC right has yet the inconsistency when the embedded note has TOC inside. issue #386

**Comment by KosmosisDire** [comment] 2024-03-04 09:55
PDFs are not supported in the HTML Document mode. See #346. PDFs cannot be embedded into a file self contained. They must be fetched from a server, so they are only supported in Online Web Server export mode. There isn't really anything I can do about this.

**Comment by KosmosisDire** [comment] 2024-03-04 09:59
>The main TOC right has yet the inconsistency when the embedded note has TOC inside. issue https://github.com/KosmosisDire/obsidian-webpage-export/issues/386

How do you expect the outline to be. Now that I am looking more closely this looks correct to me. The transclusion is inside the document's top level heading. Transclusions are always nested inside their parent header. I suppose I could make an option to disable this, but this is currently the expected behavior.

**Comment by vgyenge6** [comment] 2024-03-04 10:29
https://github.com/KosmosisDire/obsidian-webpage-export/issues/362#issuecomment-1976180763I looked into the https://github.com/KosmosisDire/obsidian-webpage-export/issues/346#issuecomment-1974967093
 
 I do not quite understand 
 >because PDFs cannot be loaded in locally opened files. This is not something that I can fix it's just a limitation of opening an html file using the file:// protocol

Is it Obsidian or browser-specific or the used pdfjs viewer limitation here? For example, I can open a local PDF file in my browser using the browser Open file File menu command and then select the local folder that contains the PDF file which will open in the browser built in pdf viewer. I'm not so deep in this matter though.

**Comment by KosmosisDire** [comment] 2024-03-04 10:38
PDFs can be opened in the browser fine, that isn't the problem. I am NOT using pdfjs, obsidian is.
The problem is that PDFs cannot be embedded into a file as data. They can only embeded as a url, which isn't supported in HTML Documents mode because they are self contained and meant to be opened locally. This means there is no way to embed a PDF inside an HTML document unless that document is hosted on a web server.

**Comment by vgyenge6** [comment] 2024-03-04 10:54
Thank you I understand.

**Comment by vgyenge6** [comment] 2024-03-04 11:14
going back to here https://github.com/KosmosisDire/obsidian-webpage-export/issues/362#issuecomment-1976191190

>If Person and Person Name were level 1 headings then "full page pdf" would end up being a child of it in the outline which makes no sense.

First, that is logical if there is a heading level higher what is next to it is lower will be its child. 
Also if the embedded note has headings those be listed in the main document outline.

But examine the heading structure I listed here to better see,
What disturbs me 

Start heading at 
**Other note** is heading 5
Person (in the embedded note) is heading 1
Person name A (in the embedded note) is heading 1
(those latter will be the children of heading 5 ??? - is this logical?)
Pdf full page is heading 5
(will come at the same level as Other note - that is okay because both are at same heading level)
BaharMartonos.pdf is heading 6
(will come at same level as Pdf full page which is heading 5 ??? - rather it should come under it as its child)
Another.pdf is heading 6
(will come at same level as Pdf full page which is heading 5 ??? - rather it should come under it as its child)
Link section is heading 4
(will come at same level as Pdf full page and Other note which are heading 5 ??? - rather  it should come as their parent)

Does not seem it inconsistent? I do not know though how to resolve it. 

See the original picture at right
![Embed_note_PDF_section_1 8 0](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/1f351878-e1c8-435b-9716-b728cc988955)

**Comment by KosmosisDire** [comment] 2024-03-04 23:11
> going back to here [#362 (comment)](https://github.com/KosmosisDire/obsidian-webpage-export/issues/362#issuecomment-1976191190)
> 
> > If Person and Person Name were level 1 headings then "full page pdf" would end up being a child of it in the outline which makes no sense.
> 
> First, that is logical if there is a heading level higher what is next to it is lower will be its child. Also if the embedded note has headings those be listed in the main document outline.
> 
> But examine the heading structure I listed here to better see, What disturbs me
> 
> Start heading at **Other note** is heading 5 Person (in the embedded note) is heading 1 Person name A (in the embedded note) is heading 1 (those latter will be the children of heading 5 ??? - is this logical?) Pdf full page is heading 5 (will come at the same level as Other note - that is okay because both are at same heading level) BaharMartonos.pdf is heading 6 (will come at same level as Pdf full page which is heading 5 ??? - rather it should come under it as its child) Another.pdf is heading 6 (will come at same level as Pdf full page which is heading 5 ??? - rather it should come under it as its child) Link section is heading 4 (will come at same level as Pdf full page and Other note which are heading 5 ??? - rather it should come as their parent)
> 

Ah wait so the heading 5 is not part of the transclusion? But yes person and person nameA should be children of heading level 5. That is how it is in the document. If you collapse the heading level 5 the transclusion should close with it. This is because the heading 1s are part of a seperate document. So the correct nesting would be

Heading 1
   Heading 5
      Heading 1 (transclusion)
      Heading 1 (transclusion)
   Heading 5
      Heading 6
      
etc...


So yes I see how it is currently incorrect. But the transclusion should be nested like that.

**Comment by vgyenge6** [comment] 2024-03-05 08:39
Hi,

>So yes I see how it is currently incorrect. But the transclusion should be nested like that.
I haven't seen this incorrect behavior, but I will try to reproduce it using your example.

You explained somewhere "transclusion" refers to embedding what should be nested. Okay.

However, I can see the problem would be in the HTML file the headings are generated correctly as Hn tags, but in the TOC right those are programmatically generated 
```
<div class="tree-item is-collapsed" data-depth="5"><a class="tree-item-self is-clickable" href="#Other_note" data-path="#Other_note">
<div class="tree-item-inner heading-link" heading-name="Other note">Other note</div></a><div class="tree-item-children"></div></div>
```
Although the  data-depth="n" might be well generated or not in the case of transclusion the indentation in the TOC list does not follow the depth. 
Might be both an algorithmic and styling problem?

Unfortunately, I can not upload the original HTML file here thus you can only examine the attached screenshot
![Embed_note_TOC_inconsistency_1 8 1 2b](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/bde5e1ba-0fad-4835-a8eb-b2ca41de616a)

. Or try to reproduce generating the HTML output (with HTML document preset and only TOC allowed settings, invoking from the tab right context Export as HTML menu how I made it), I attached the two original md files.
[MD_obs-embedPDF_and_section.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/14492579/MD_obs-embedPDF_and_section.md)
[Person_template.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/14492583/Person_template.md)

**Closed** 2024-03-20 16:27 UTC
