### ISSUE TITLE
Embedded links in obsidian is not exported

### ISSUE THREAD

**Issue by Scofield-Gu** [KosmosisDire/obsidian-webpage-export#262] opened 2023-10-12 10:16 UTC
**Describe the bug**
Embedded links in obsidian is not exported, i'm using the feature below in obsidian. And I expect to export this feature in webview
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/53439623/40d929d6-636b-426a-ac44-bcd26f598405)

**Operating System**
plugin version 1.7.3
obsidian version 1.4.14

**To Reproduce**
Steps to reproduce the behaviour:
1. write ![[source.md#heading1]] in main.md
2. write ![[source.md#^e69785]] in main.md
3. export to webpage via the plugin
4. nothing is exported in the html

**Screenshots**
If applicable, add screenshots here to help explain your problem (just copy paste)
here's the original form in markdown file in obsidian
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/53439623/a20f6b70-e257-4561-8c35-e5b00d6e55e6)
here's the web view
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/53439623/02285ec4-74d8-4b9b-9150-fc541509d7cb)

### IMPORTANT: Error Log
1. Please open the developer console using (Ctrl + Shift + I), and clear the console using the button at the top left corner.
2. Reproduce the bug
3. Take a screenshot orcopy the error from the console if it has any output and paste it here

**Comment by KosmosisDire** [comment] 2023-10-12 12:41
Hi thanks, this is a duplicate of #207 so I will close this in favor of that issue. However, this problem will be fixed in the next update

**Closed by KosmosisDire** 2023-10-12 12:41 UTC
Labels: bug

**Comment by Scofield-Gu** [comment] 2023-10-13 02:31
Hello KosmosisDire,really glad to know that. Thanks for your reply.
