### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by myliwenbo** [KosmosisDire/obsidian-webpage-export#92] opened 2023-05-05 03:42 UTC
##### [Fatal Error] Could not export file: xxxx.md
```
URIError: URI malformed
    at decodeURI (<anonymous>)
    at _Path.parsePath (plugin:webpage-html-export:10237:12)
    at _Path.reparse (plugin:webpage-html-export:10216:24)
    at new _Path (plugin:webpage-html-export:10203:10)
    at eval (plugin:webpage-html-export:10589:14)
    at Array.map (<anonymous>)
    at GraphGenerator.getGlobalGraph (plugin:webpage-html-export:10588:19)
    at HTMLGenerator.fillInHead (plugin:webpage-html-export:11849:33)
    at HTMLGenerator.generateWebpage (plugin:webpage-html-export:11722:16)
    at async HTMLExportPlugin.exportFile (plugin:webpage-html-export:12306:7)
```

**Comment by myliwenbo** [comment] 2023-05-05 03:44
![image](https://user-images.githubusercontent.com/29202248/236373556-797d6943-cf04-40b3-acdb-e92264739801.png)
Turning this option on causes problems

**Comment by KosmosisDire** [comment] 2023-05-05 06:34
I am following a similar problem in #78, thanks for your report. How many notes do you have in your vault? Also would you be willing to share your vault by any chance so I can reproduce this issue? Because I am unable to reproduce it

**Comment by KosmosisDire** [comment] 2023-05-30 02:06
I beleive this problem should be fixed in the latest update, but let me know if you still have problems!

**Closed by KosmosisDire** 2023-05-30 02:06 UTC
Labels: bug
