### ISSUE TITLE
page width setting

### ISSUE THREAD

**Issue by smallwerke** [KosmosisDire/obsidian-webpage-export#89] opened 2023-05-04 16:14 UTC
Setting the page width during export doesn't appear to work anymore. The html results in expanded space between the content and the sidebar with the header list but the width of the actual content remains the same as when it is set to default, there is now an empty column of space between the content and the document outline. I've tried adjusting numerous settings with no effect. Seeing the same results in both firefox & safari.

**Comment by KosmosisDire** [comment] 2023-05-04 21:47
Hey I am unable to reproduce this, it works for me. Could you export a document with a width of 300px (or any other specific width that you tell me) and send me the exported html that isn't working?

**Comment by KosmosisDire** [comment] 2023-05-05 17:26
Hey, all of these files work for me! I am testing in both Firefox and Chrome

300px
![image](https://user-images.githubusercontent.com/39423700/236525162-f271c65d-cac8-4444-bf5e-ddebdf7d3ab5.png)

1200px
![image](https://user-images.githubusercontent.com/39423700/236525271-9260e388-711c-49b1-911b-bad75f7cadb4.png)


Btw the weird spacing a uncentered document when the page width is high should be fixed in the next release. Is that the problem you are having where the page won't get larger than a certain amount?

**Comment by smallwerke** [comment] 2023-05-08 15:25
yeah, it's that blank column when the width is set higher where the content section doesn't expand but the full width of the document does but if that's fixed in the next release that's awesome, for some reason I remember it behaving differently on a previous release which is why I submitted it as a bug but that could also just be my memory...

**Closed** 2023-05-30 01:54 UTC
Labels: bug

**Comment by KosmosisDire** [comment] 2023-05-30 02:03
This is fixed in update 1.6.0, and layout options have been added. Let me know if you have any more problems! And thanks for the report :)
