### ISSUE TITLE
[Bug]: Note tittles in a canva export with a white box under them

### ISSUE THREAD

**Issue by Grmglib** [KosmosisDire/obsidian-webpage-export#506] opened 2024-09-17 21:55 UTC
### What happened?

Note tittles in a canva export with a white box under them

### Reproduction

Add a note to a canva and export as a unique html file

### Version

0.5.2

### Operating System

Windows 11

### Obsidian Version

v1.6.7

### Which browsers can you reproduce this in?

Firefox, Chrome

### Relevant log output

```yaml
Log:
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[WARNING] 	Creating an RSS feed requires a site url to be set in the export settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing export metadata found. All files will be exported.
[WARNING] 	No existing search index found. All files will be exported.
[WARNING] 	No existing RSS feed found. All files will be exported.
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing search index found. All files will be exported.
[INFO] 	No old files to delete
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing search index found. All files will be exported.
[INFO] 	No old files to delete
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing search index found. All files will be exported.
[INFO] 	No old files to delete
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing search index found. All files will be exported.
[INFO] 	No old files to delete
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing search index found. All files will be exported.
[INFO] 	No old files to delete
[INFO] 	Closing render window
[WARNING] 	For Excalidraw embed support, set the embed mode to "Native SVG" in the Excalidraw plugin settings.
[INFO] 	Including stylesheet: 
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-1widvzq-style
[WARNING] 	No existing search index found. All files will be exported.
[INFO] 	No old files to delete
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.01
	makeOfflineCompatible     false
	inlineAssets ------------ true
	includePluginCSS          9 plugins included
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth -----------
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	allowFoldingHeadings ---- true
	allowFoldingLists         true
	allowResizingSidebars --- true
	logLevel                  warning
	minifyHTML -------------- true
	makeNamesWebStyle         false
	onlyExportModified ------ true
	deleteOldFiles            true
	addThemeToggle ---------- true
	addOutline                true
	addFileNav -------------- true
	addSearchBar              false
	addGraphView ------------ false
	addTitle                  true
	addRSSFeed -------------- false
	siteURL                  
	authorName --------------
	vaultTitle                Main
	exportPreset ------------ documents
	openAfterExport           false
	graphAttractionForce ---- 1
	graphLinkLength           10
	graphRepulsionForce ----- 150
	graphCentralForce         3
	graphEdgePruning -------- 100
	graphMinNodeSize          3
	graphMaxNodeSize -------- 7
	showDefaultTreeIcons      false
	emojiStyle -------------- Native
	defaultFileIcon           lucide//file
	defaultFolderIcon ------- lucide//folder
	defaultMediaIcon          lucide//file-image
	exportPath -------------- D:\\\\Downloads
	filesToExport             1


Enabled Plugins:
	Homepage
	Smart Connections
	Highlightr
	Execute Code
	Tasks
	Excalidraw
	Omnisearch
	Text Extractor
	Diagrams.net
	Mind Map
	Reminder
	Dataview
	Quick Tagger
	Auto Note Mover
	Tasks Calendar Wrapper
	Find orphaned files and broken links
	Iconize
	Calendar
	Advanced Canvas
	Webpage HTML Export
```

### Additional Info

![image](https://github.com/user-attachments/assets/2074119f-9e44-456c-9b34-0f18000bc34b)
![image](https://github.com/user-attachments/assets/756424e6-76b9-46b9-8934-d15e5abacca9)

**Comment by KosmosisDire** [comment] 2024-09-17 22:46
I am going to guess this is caused by some plugin you are using, however you can test in the beta to see if this is fixed (there are a lot of bugs fixed in the beta). Instructions to install the beta are in the Readme. 

You can also try to reproduce this without any plugins to see if there is something conflicting with a plugin.

**Comment by Grmglib** [comment] 2024-09-17 23:33
It was the iconize plugin, thanks for the fast answer. Now i am trying to find a way to use both plugins at the same time

**Comment by KosmosisDire** [comment] 2024-09-17 23:49
The plugin has official Iconize support actually. I use iconize and do not have problems with my canvas exports. How are you using the Iconzie plugin?

**Comment by Grmglib** [comment] 2024-09-18 00:55
I didn't change a lot of the default settings, just added icon in tabs and next to title, and i am using the native icons.
Now i tested again and i think it was a bug with some sort of conflict with the google drive folder where my vault is.
I tested with some different configs and know everything is working. Don't know why.

**Comment by KosmosisDire** [comment] 2024-09-18 01:31
Huh, I am not sure what was wrong but glad it is working! I will go ahead and close this, but feel free to create another issue if you have any more problems. :)

**Closed by KosmosisDire** 2024-09-18 01:31 UTC
Labels: bug
