### ISSUE TITLE
HTML DOM anchors of Markdown headers are not rendered properly

### ISSUE THREAD

**Issue by XinYaanZyoy** [KosmosisDire/obsidian-webpage-export#165] opened 2023-07-29 21:42 UTC
**Describe the bug**
- `site/page.html#id1` brings the page `site/`
- clicking on the toc works but copying its link copies `site/#subtitle` instead of `site/page.html#subtitle`

**Comment by KosmosisDire** [comment] 2023-07-31 17:24
Thank you for this. So to clarify the problem is that when a link's address is copied it does not copy the actual page that that link directs to, right?

**Comment by XinYaanZyoy** [comment] 2023-08-03 18:55
yeah, it doesn't copy the link to "an anchor" on the page. and also, it seems the site/page.html#id doesn't seem to be implemented which is very important for any website especially the kinds we build out of obsidian projects. when you type site/page.html/#id you get "kinda redirected" to site/.

so there are two issues here. the copying problem is easier to solve I think, but you might, if I am right (not exactly sure), need to rethink the whole design to actually make the copied link work.

**Comment by KosmosisDire** [comment] 2023-08-03 18:57
I think I should be able to fix both of these pretty easily. I think the problem is due to the way I am overriding the normal loading process to allow new pages to be loaded without reloading the page. Thank you for reporting this bug :)

**Comment by KosmosisDire** [comment] 2024-02-20 08:10
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:10 UTC
Labels: bug, approved, reproduced
