### ISSUE TITLE
Navigating back to previous page results in 404/"Page Not Found"

### ISSUE THREAD

**Issue by RyotaUshio** [KosmosisDire/obsidian-webpage-export#295] opened 2023-12-03 07:17 UTC
**Describe the bug**

> Note: This is a little bit similar to #245, but a different one.

When I go to whatever page under some folder, navigating back to the previous page fails with 404, and it shows a message saying "Page Not Found".

**Operating System**

macOS Ventura 13.5.2

**To Reproduce**

Steps to reproduce the behavior (I have tested on Chrome and Safari):

1. Go to https://ryotaushio.github.io/obsidian-math-booster/. This is a website generated using this plugin.
2. From the file tree, go to whatever page that is located under some folder. For example, "Theorem callouts > Styling".
3. Now, click the "navigate back" button of the browser.
4. You will see a message saying "Page Not Found".

**Screenshots**

<img width="1434" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/72342591/7f97c9e9-4813-4b58-96fb-89b8762ba7c0">

### IMPORTANT: Error Log

- When I went to `index.html` > `theorem-callouts/styling.html` and then navigated back:

  <img width="545" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/72342591/d306a340-6527-4b46-a6b1-9c1f2977ca69">

- When I went to `index.html` > `equations.html` > `theorem-callouts/styling.html` and then navigated back:

  <img width="545" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/72342591/e9a94734-ea46-4e75-b11d-4e9c7925ab58">

Looks like the requested URL has a redundant `obsidian-math-booster`.

**Comment by RyotaUshio** [comment] 2023-12-03 10:48
It seems that this happens only when the previous page and the current page have different depths.

**Comment by RyotaUshio** [comment] 2023-12-03 10:52
Maybe it's this function?

https://github.com/KosmosisDire/obsidian-webpage-export/blob/d232ca561b2feaa68147090a4cfce867853672a7/assets/webpage.txt.js#L808

**Comment by KosmosisDire** [comment] 2023-12-04 19:57
Hi, thanks I have also encountered this and it seems to have been caused in the update to 1.7 at some point. I think it is likely something wrong with the way going back is handled and the relative paths getting out of sync (because all the relative paths are calculated by "deltas" if that makes sense. I will look into fixing this in the next update. Feel free to look into it more and thanks again :)

**Comment by royalknight56** [comment] 2024-02-06 06:47
any solution?

**Comment by KosmosisDire** [comment] 2024-02-06 06:49
> any solution?
This is fixed in the beta, you can wait for the stable release or download the beta now

**Comment by KosmosisDire** [comment] 2024-02-06 06:50
You can see the latest beta here: https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.8.0-9b

**Comment by royalknight56** [comment] 2024-02-06 06:55
> > any solution?
> 
> This is fixed in the beta, you can wait for the stable release or download the beta now

I installed  1.8.0-9b, the problem still seems to exist

**Comment by royalknight56** [comment] 2024-02-06 06:58
my folder:

note
 | a.md
 | b.md
index

**Comment by KosmosisDire** [comment] 2024-02-06 07:06
Does this only happen for the first page? AKA you enter the site, navigate somewhere, go back and it throws an error? Or it happens even if you naviagte to a bunch of pages first and then go back? Could you step me though the exact buttons you click on and in what order to reproduce it?

**Comment by royalknight56** [comment] 2024-02-06 07:16
> Does this only happen for the first page? AKA you enter the site, navigate somewhere, go back and it throws an error? Or it happens even if you naviagte to a bunch of pages first and then go back? Could you step me though the exact buttons you click on and in what order to reproduce it?

My export mode is Online Web Server。

after export，I started a http-server。

I first visit http://localhost:5500/ , the index will be displayed, then click on other pages, and then click the chrome back button,

The browser will automatically download an html file, and the index will not be displayed.

**Comment by KosmosisDire** [comment] 2024-02-06 07:18
Ah okay so it's not the 404 error it's the download problem. Try going to http://localhost:5500/index.html instead and see if the problem still persists. I will try and solve the download problem too in the next stable release

**Comment by KosmosisDire** [comment] 2024-02-20 08:25
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:25 UTC
Labels: bug
