### ISSUE TITLE
Svgs are not inlined properly

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#55] opened 2023-04-01 14:55 UTC
When exporting a document with svg images rendered by other plugins, they don't show up 

With inlining
![image](https://user-images.githubusercontent.com/34401005/229296544-741259dc-2019-400f-8dc5-614e5d5cfd2d.png)

Without inlining:
![image](https://user-images.githubusercontent.com/34401005/229296583-8d09b735-ff0c-4f52-8319-e8a4be2587b7.png)

**Comment by KosmosisDire** [comment] 2023-04-02 01:23
This is a duplicate of #45 and has been fixed in the master branch. When I make a release this will be fixed.

Thanks for the report.

**Comment by lycfly** [comment] 2023-04-07 06:13
I'm also having the same issue. I tried clone the master branch and put it into obsidian's plugin folder, but the plugin doesn't work.
By the way is there a new release in the near future?

**Comment by KosmosisDire** [comment] 2023-04-07 17:43
> I'm also having the same issue. I tried clone the master branch and put it into obsidian's plugin folder, but the plugin doesn't work. By the way is there a new release in the near future?

If you clone the repo directly you have to also build the project from typescript into js, you can't only clone it. Also keep in mind that the master branch has other changes as well, some of which are preliminary and may break other things. 

I can't guarentee a release date, however there will likely be one this month.

**Comment by KosmosisDire** [comment] 2023-04-29 10:45
This should be fixed in the latest update. Thanks for the report and let me know if you find any other problems! 😊

**Closed by KosmosisDire** 2023-04-29 10:45 UTC
Labels: bug
