### ISSUE TITLE
Disabling the search bar in new v1.8.0-2b results in no content displaying

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#327] opened 2024-01-29 16:21 UTC
**Describe the bug**
Disabling the search bar in [v1.8.0-2b](https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.8.0-2b) breaks webpage display --  both sidebars start out minimized, but no content is visible in the middle. Clicking on anything in the sidebars does nothing.

**Operating System**
Fedora Linux

**To Reproduce**
See screenshots for settings:
![export-settings](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/2e80078e-9e35-47d0-8eaf-e4cad7450c33)
![export-settings2](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/2996f423-3769-4b0d-aa6b-ac12f384c6b1)

Then I of course used the "Online Web Server" export mode.

**Screenshots**
![no-content](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/90cb7d79-f63b-4674-9ad9-ec9d95d85904)
Even better: for a live example of my vault exported with these settings and displaying this issue, go to [b19.org/testjunk](https://b19.org/testjunk/)

### IMPORTANT: Error Log
![console](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/d3b78633-08f3-4d2a-a46f-a627014681c5)

**Comment by ryran** [comment] 2024-01-29 16:22
_Aside: I actually like the idea of a search bar and would be happy for it to always be there if it had an index of the whole site and worked properly. I don't know what it's **meant** to do (maybe the feature is still a WIP), but it doesn't seem to work with my content. Sometimes it can find words in headings, but only in the currently-displayed page and never any non-heading text... and it displays the results on the right-hand side above the TOC, which is very weird. So that's why I was disabling it (to avoid confusing users, since it seems to work even less well than Ctrl-f)._

**Comment by KosmosisDire** [comment] 2024-01-29 20:51
Yes I noticed that on your site the search was broken, very weird! It doesn't do that on all the tests I've done. I'll also look into making sure the export doesn't break with the search disabled!

**Comment by ryran** [comment] 2024-01-29 23:39
One other _aside_ question for you Nathan: I noticed that there's no longer an option to start with all headings collapsed. Just curious: was it on purpose (for whatever reason) or just somehow an oversight?

**Comment by ryran** [comment] 2024-01-30 02:06
Ooo I just noticed that in the TOC, anchor links to headings which have accent marks (or maybe extended characters in general?) fail to work. You can see this most obviously by going to [this page](https://b19.org/bah%C3%A1%E2%80%99%C3%AD-library-authoritative-writings-and-guidance.html). You'll notice the single H1 link doesn't work and neither do 3 of the H2 links. Should I open a new bug to track this?

**Comment by KosmosisDire** [comment] 2024-01-30 02:16
I removed the start with all headers collapsed option because I figured no one would ever use it lmao
But I can certainly add it back in if you were finding that useful. You certainly have very long files. Either way maybe it would be better if you seperated your huge file into individual files, and sorted them into a folder of general resources instead. I think that would make it much easier to navigate. But I will add back the start collapsed option.

**Comment by KosmosisDire** [comment] 2024-01-30 02:19
> Ooo I just noticed that in the TOC, anchor links to headings which have accent marks (or maybe extended characters in general?) fail to work. You can see this most obviously by going to [this page](https://b19.org/bah%C3%A1%E2%80%99%C3%AD-library-authoritative-writings-and-guidance.html). You'll notice the single H1 link doesn't work and neither do 3 of the H2 links. (To be clear, this isn't an issue in Obsidian itself.) Should I open a new bug to track this?

Bahá’í
This word is triggering it most often. It is actually caused by this character: `’` not by the accented characters. Try using an apostrophe instead for now `'`. I will look into fixing this though!

**Comment by ryran** [comment] 2024-01-30 02:33
> Bahá’í
> This word is triggering it most often. It is actually caused by this character: `’` not by the accented characters. Try using an apostrophe instead for now `'`. I will look into fixing this though!

Ohhh interesting. Thanks. Sorry to muddy up this issue with that. I posted a new one for tracking.

**Comment by ryran** [comment] 2024-01-30 02:39
> I removed the start with all headers collapsed option because I figured no one would ever use it lmao But I can certainly add it back in if you were finding that useful. But I will add back the start collapsed option.

Oh wow OK. Well obviously I can't speak for anyone else so it's your call, but I personally love that option when I'm looking at big docs that have a TOC. :)

> You certainly have very long files. Either way maybe it would be better if you seperated your huge file into individual files, and sorted them into a folder of general resources instead. I think that would make it much easier to navigate. 

Yes I totally get what you mean about splitting up into pages and appreciate the advice; however, this is meant to be a single page to allow folks to immediately jump to what they want without navigating through a tree. All the content I'm linking to on the above-mentioned page is already available in a more traditional tree format starting at [bahai.org/library](https://www.bahai.org/library/) ... where it normally takes clicking through 3 pages to get to any content you want, so putting it all in one place where a single click gets you there is very much intentional.

**Comment by ryran** [comment] 2024-01-30 07:46
Here's a question: is it somehow incorrect to use bold on headers? Obsidian doesn't have a problem with it when previewing or in reading mode (font weight is appropriately increased and TOC still works, at least in my theme), but when I use your plugin to export a doc with emboldened H1, I get warnings like in the attached screenshot, and it creates a second H1 for each doc.
![things](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/e5851939-2792-4031-a178-7900a8a6011a)

Note: I haven't had H1 in bold before tonight, but I have always some H2 headings in bold ... maybe that could be causing some other problems...

**Comment by KosmosisDire** [comment] 2024-01-30 09:02
> Here's a question: is it somehow incorrect to use bold on headers? Obsidian doesn't have a problem with it when previewing or in reading mode (font weight is appropriately increased and TOC still works, at least in my theme), but when I use your plugin to export a doc with emboldened H1, I get warnings like in the attached screenshot, and it creates a second H1 for each doc. ![things](https://private-user-images.githubusercontent.com/1092618/300719874-e5851939-2792-4031-a178-7900a8a6011a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDU1MzMsIm5iZiI6MTcwNjYwNTIzMywicGF0aCI6Ii8xMDkyNjE4LzMwMDcxOTg3NC1lNTg1MTkzOS0yNzkyLTQwMzEtYTE3OC03OTAwYThhNjAxMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDkwMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDgzZTA5NDY5NmU5MzJlNDFiZDRkMTFiY2Q1YWRmYmVjZDk5MGQ2Y2MyMzYxNmQxNWJlMDVhNDI2MWRhMzEwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._O6HFgL0Yyg1Nia18LwLO-0SUrEUJ2KXRyItnt_u824)
> 
> Note: I haven't had H1 in bold before tonight, but I have always some H2 headings in bold ... maybe that could be causing some other problems...

Ahh interesting, good catch. I hadn't thought of this. Bold should be supported, that is just a problem with the way I am parsing the text of the first header in each document which is interrupted by the bold. I will fix that. If you could make a new issue for that it would be very helpful. Thanks!

**Comment by KosmosisDire** [comment] 2024-02-02 01:32
Test this on 1.8.0-3b and let me know how it works

**Comment by ryran** [comment] 2024-02-02 03:13
> Test this on 1.8.0-3b and let me know how it works

## In online web-server mode:
With the following settings, it still behaves the same, i.e., fails to show any content.
![online-1](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/021563db-0f6b-4b75-96ec-3cd4227d105a)
![online-2](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/9d43ef64-310f-4bba-ac95-638ca4fec097)

## In raw html documents mode:
Content is visible.. I believe it wasn't before.

## In html documents mode:
Content is now visible.

**Comment by KosmosisDire** [comment] 2024-02-02 07:07
Hey, could you try this again on 1.8.0-5b? Thanks!

**Comment by ryran** [comment] 2024-02-02 18:02
> Hey, could you try this again on 1.8.0-5b? Thanks!

I just tested 1.8.0-7b in online webserver mode with search disabled.  It works -- with or without file tree enabled.

(Aside: I personally want the filetree, but FYI I also noticed that with file tree disabled + theme selector enabled, the left sidebar now gets hidden, so no theme selector in that particular case.)

**Comment by KosmosisDire** [comment] 2024-02-02 18:18
Ah good catch I'll fix that

**Comment by KosmosisDire** [comment] 2024-02-05 01:09
The no theme toggle issue should be fixed in 1.8.0-9b. I am fairly certain it works so I will close this but let me know if it doesn't work

**Closed by KosmosisDire** 2024-02-05 01:09 UTC
Labels: bug
