### ISSUE TITLE
Ctrl+Clicking a link doesn't open the page in a new tab

### ISSUE THREAD

**Issue by lowlight-ua** [KosmosisDire/obsidian-webpage-export#264] opened 2023-10-13 16:17 UTC
**Describe the bug**

* Export a vault to HTML.
* Ctrl+Click a link.

Expected: the page is opened in a new tab (standard browser behavior). 
Actual: the page is opened in the same tab.

Middle-clicking works properly.

**Operating System**

Windows 10.

**To Reproduce**

Ctrl+click on any link in the generated vault HTML.

### IMPORTANT: Error Log

Not applicable; happens in the browser when viewing the page. (No console output in the browser.)

**Comment by KosmosisDire** [comment] 2023-10-13 17:07
Hi thanks, this is a duplicate of #190 so I'll close this in favor of that one.

**Closed** 2023-10-13 17:07 UTC
Labels: bug
