### ISSUE TITLE
Selecting 'no special page features embedded' in settings produces HTML output, but it does not show anything in the browser

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#285] opened 2023-11-21 10:47 UTC
Hi,

First of all, it is a great plugin. Thanks for it.

I would like to export the content of the page without adding any sidebars (outline and page navigation, UI set dark/light). I disabled these in the settings, expecting it will only export the page content.
However, selecting 'no special page features embedded' in settings produces an HTML output, but it does not show anything in the browser even if it has content when I see the page source.
It is very strange :)

Thank you for looking after it.
![Settings_no_special_features_selected_2023-11-21](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/f7bbb28c-1924-47c8-9469-c5d39f904ae1)

**Operating System**
WIN 10 Pro
Obsidian  v.1.4.16
your plugin v. 1.7.3

**Comment by KosmosisDire** [comment] 2023-11-21 16:22
This is a known bug that is caused by turning off the theme toggle, will be fixed in the next update

**Comment by vgyenge6** [comment] 2023-11-22 09:56
> This is a known bug that is caused by turning off the theme toggle, will be fixed in the next update

Thanks. I hope the next update is soon. :)
I think it is a very crucial feature, I mean only exporting a single note content in HTML format, without any additional embedding, because obsidian doesn't give this feature inbuilt ( Export to HTML) similarly as Export to PDF has given.

_My note_: That perhaps would be simplified if the adding any sidebars (outline and page navigation, UI set dark/light). are disabled in the settings, and your Export as HTML has invoked from the active note right context menu, so it would not be necessary to hook up the Selection from Structure either. Those settings can mean only that note content will be exported. That is an else case when the Export as HTML has invoked from the Explorer context menu. 

Thank you for considering this too.

**Comment by KosmosisDire** [comment] 2024-02-20 08:23
This bug has been fixed in 1.8.0! :)
If you find any issues please create a new issue
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:23 UTC
Labels: bug

**Comment by vgyenge6** [comment] 2024-02-21 10:10
Hi,

Thank you, it works now well. 👍

**Comment by vgyenge6** [comment] 2024-02-21 10:20
Hi,

Thank you, it works now well. 👍
