### ISSUE TITLE
Add Iteration through internally linked Documents

### ISSUE THREAD

**Issue by JonaHesselmann** [KosmosisDire/obsidian-webpage-export#282] opened 2023-11-18 17:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently it is (with my current knowledge) to select a File and export the file with all linked Files. 

**Describe the solution you'd like**
an option to export a file with all internally linked files. (maybe set with a depth limit ). that Way you do not get file not found errors when exported.

**Describe alternatives you've considered**
exporting whole folders, but some users do not organize their Vault with Folders
**Additional context**

**Comment by KosmosisDire** [comment] 2023-11-21 19:04
This is a duplicate of #38

**Closed by KosmosisDire** 2023-11-21 19:04 UTC
Labels: enhancement
