### ISSUE TITLE
Error when exporting notes including attachments whose filename contains percentage sign

### ISSUE THREAD

**Issue by alberti42** [KosmosisDire/obsidian-webpage-export#246] opened 2023-10-01 13:52 UTC
**Describe the bug**
URIError. Could not decode path of attachments when the filename of the attachment contains percent sign `%`. 

**Operating System**
MacOS

**To Reproduce**
Create a note with an attachment whose name contains the percent sign and export the note as HTML.

### IMPORTANT: Error Log

I use the percent sign in the filename to keep track of certain parameters expressed as percentage. When I export the note, I get errors as shown below:

```
##### [Error] Could not decode path:1 Daily notes/2023-09-20 Fast gates, square pulse analysis (attachments)/PhaseSpaceTrajectory_PulseType=SquarePiOver2_TrapFreq=100.0kHz_TrapFreqDev=0.0%_NTrap=1_Rabi=20.0kHz_IntDev=0.0%_NLaser=1_T=12.5us_Nt=300_c=11.7_GSprob=0.9_NFocks=50_NFourier=0_WEnt=10.0_WMot=10.0_coherent.gif

URIError: URI malformed
    at decodeURI (<anonymous>)
    at _Path.parsePath (plugin:webpage-html-export:48738:14)
    at _Path.reparse (plugin:webpage-html-export:48716:24)
    at new _Path (plugin:webpage-html-export:48703:10)
    at new FileTree (plugin:webpage-html-export:55496:20)
    at new FilePickerTree (plugin:webpage-html-export:56927:5)
    at ExportModal.open (plugin:webpage-html-export:57090:25)
    at eval (plugin:webpage-html-export:57407:36)
    at e.handleEvent (app://obsidian.md/app.js:1:888522)
    at click (app://obsidian.md/app.js:1:895046)
    at CallbacksRegistry.apply (/Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54:29)
    at /Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js:346:23
    at EventEmitter.<anonymous> (/Applications/Obsidian.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js:328:13)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9266)
```

**Comment by KosmosisDire** [comment] 2023-10-01 20:26
This is a duplicate of #225

**Closed by KosmosisDire** 2023-10-01 20:26 UTC
Labels: bug
