### ISSUE TITLE
Weird list padding

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#72] opened 2023-04-29 16:32 UTC
In some cases list spacing is bigger than in obsidian

In obsidian:
![image](https://user-images.githubusercontent.com/34401005/235313378-5cc63816-1c7c-4564-a734-d7f292c70b00.png)

In export:
![image](https://user-images.githubusercontent.com/34401005/235313388-7f6eb417-53b2-4e2d-ae63-8ad64dc45b6e.png)

I suspect that's because of this margin: 
![image](https://user-images.githubusercontent.com/34401005/235313419-a58b464e-8e8a-4461-8bc7-248e75cf7ec6.png)

**Comment by KosmosisDire** [comment] 2023-04-29 18:20
Huh interesting, I'll look into it thanks!

**Comment by KosmosisDire** [comment] 2023-04-29 18:33
What theme are you using? I cannot reproduce this

**Comment by dgudim** [comment] 2023-04-30 10:10
I was able to reproduce this in a sandbox with only the export plugin

Obsidian:
![image](https://user-images.githubusercontent.com/34401005/235347391-bc25e663-fd20-4dc7-9495-8aad2907da9c.png)

Export:
![image](https://user-images.githubusercontent.com/34401005/235347404-c5b1fa5d-37a9-48d1-8f5b-4ec95d6b2710.png)

Here is the test file: [Test.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/11361050/Test.md)

And I think i found the culprit, if you remove this newline 
![image](https://user-images.githubusercontent.com/34401005/235347516-704c68fb-9c43-4aa5-b2d4-f1e504cfd6ff.png)
The issue is no longer there, so I'll use this fix for now

**Comment by KosmosisDire** [comment] 2023-04-30 19:17
Thanks for the simple reproduction instructions! This seems to be caused by the background renderer not adding the class "has-list-bullet` to bulleted lists

**Comment by KosmosisDire** [comment] 2023-05-01 19:58
I am going to replace the background exporter with a different method which will be slightly slower but will have all the same features as the old exporter, but it should be more stable and allow you to keep using obsidian while it exports. Once that comes out this should be fixed.

**Comment by KosmosisDire** [comment] 2023-05-01 22:03
This should be fixed in version 1.5.1. Thanks for the report!

**Closed by KosmosisDire** 2023-05-01 22:03 UTC
Labels: bug
