### ISSUE TITLE
I can't enable the plugin.

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#193] opened 2023-09-11 10:02 UTC
**Describe the bug**
Everytime I enable it, it just errors.

**Operating System**
Windows 10

**To Reproduce**
1. Install the new version of Obsidian which is v1.4.5
2. Install Webpage Export.
3. Enable it.

### IMPORTANT: Error Log
Pugin failure: webpage-html-export SyntaxError: Unexpected token ')'

**Comment by joeymichalik** [comment] 2023-09-11 10:16
same here

**Comment by KosmosisDire** [comment] 2023-09-11 10:17
Hmm very strange, I have tried downloading it from scratch into a vault and it works fine. Could you try uninstalling and reinstalling the plugin?

**Comment by joeymichalik** [comment] 2023-09-11 10:19
Still the same error, after reinstalling the plugin

**Comment by I2rys** [comment] 2023-09-11 10:20
> Hmm very strange, I have tried downloading it from scratch into a vault and it works fine. Could you try uninstalling and reinstalling the plugin?

Same output. 🤔

**Comment by KosmosisDire** [comment] 2023-09-11 10:21
Could you send me a screenshot of the console with the error?

**Comment by I2rys** [comment] 2023-09-11 10:22
> Could you send me a screenshot of the console with the error?

Sure!
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/87125939/453104de-f187-4770-86be-7e5d984408f3)

**Comment by KosmosisDire** [comment] 2023-09-11 10:33
This is very weird, I am not sure what is happening. The lines it gives are not missing any parenthesis as far as I can tell and I cannot reproduce this :/

**Comment by KosmosisDire** [comment] 2023-09-11 10:38
I am able to reproduce it on a seperate computer, I'll look into this but I have no leads on what is causing this for now

**Comment by I2rys** [comment] 2023-09-11 10:41
> This is very weird, I am not sure what is happening. The lines it gives are not missing any parenthesis (nor do they have extra parenthesis) as far as I can tell and I cannot reproduce this :/

Hmmm perhaps It's the way you bundled it? Or it needs a dependency that our PC don't have?

**Comment by given-woo** [comment] 2023-09-11 10:54
Same here (with Obsidian 1.4.5 on Macos Sonoma 14.0)

**Comment by KosmosisDire** [comment] 2023-09-11 10:54
I guess I will just delete the release for now, until I figure out what is going on

**Comment by KosmosisDire** [comment] 2023-09-11 10:57
> > This is very weird, I am not sure what is happening. The lines it gives are not missing any parenthesis (nor do they have extra parenthesis) as far as I can tell and I cannot reproduce this :/
> 
> Hmmm perhaps It's the way you bundled it? Or it needs a dependency that our PC don't have?

The bundling is automated, so it does it the same every time. It is likely some weird dependency thing, but I can't imagine how it could be dependent on my computer.

**Comment by AE-BASOL** [comment] 2023-09-11 12:11
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/87247367/25be07c3-26a6-4fbc-87e7-bc0564b6ba5a)
I can't update it either. Version 1.4.5

**Comment by I2rys** [comment] 2023-09-11 12:13
> 

Due to the current issue of the v1.7.0 he removed the packaged for now until It's resolved.

**Comment by KosmosisDire** [comment] 2023-09-11 22:50
This is resolved with 1.7.1

**Closed by KosmosisDire** 2023-09-11 22:50 UTC
Labels: bug

**Comment by henusys** [comment] 2023-09-12 01:07
Yes，I can't export it correctly, which show me an error.
![1694480835813](https://github.com/KosmosisDire/obsidian-webpage-export/assets/9565297/151a275c-37b7-4cd0-a3b9-2aa201c39636)

**Comment by KosmosisDire** [comment] 2023-09-12 01:11
> @henusys  Yes, I can't export it correctly, which show me an error. ![1694480835813](https://user-images.githubusercontent.com/9565297/267181437-151a275c-37b7-4cd0-a3b9-2aa201c39636.jpg)

Hi this is a different issue altogether, can you create a new issue and include more information? Thanks!
