### ISSUE TITLE
A file downloads by the browser when the user opens my website

### ISSUE THREAD

**Issue by dev-amira-ezz** [KosmosisDire/obsidian-webpage-export#245] opened 2023-09-29 00:44 UTC
**Describe the bug**
I have uploaded the generated HTML folder to my public_html folder on my website. The whole site is working fine. The problem is that it downloads a file (it's an HTML file). I tried the website on my phone, tablet and linux computer and they all produced a file and downloaded it (sometimes asking for user's permission). 
This is the name of the file downloaded to my computer: RpZX1tXR.html

**Operating System**
MX Linux 23, Android 12 (tablet), and Android 13 (phone).
My website is on Bluehost.

**To Reproduce**
1. Go to '[useful notes](https://usefulnotes.info/)'. This is my website generated by your plugin.
2. Click on 'Just navigate through the links for a while'
4. The file will start downloading or ask for permission.

**Comment by KosmosisDire** [comment] 2023-09-29 02:37
Interesting, I am able to reproduce this. Thanks! I will look into fixing this.

**Comment by amira-ezz-eldin** [comment] 2023-09-29 11:15
Thank you. 
I've tested my Bluehost server by sharing a test website with simple HTML files and links between them. 
No download occurred. So I think it's not a problem with the host.

**Comment by KosmosisDire** [comment] 2023-10-09 14:15
This only happens when using the bak button to go back to the index.html page. So this should be a pretty easy fix

**Comment by KosmosisDire** [comment] 2023-12-05 22:26
This is a duplicate of #255 but i'll keep it open since you share some good resources for testing

**Comment by KosmosisDire** [comment] 2024-02-20 08:13
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!

**Closed by KosmosisDire** 2024-02-20 08:13 UTC
Labels: bug, approved, reproduced
